- mix.lock
This means that everything now works on the latest version of erlang
and elixir.
> Update erlexec from 1.7.5 to 1.9.3

- README.md
- apps/omg_eth/mix.exs
- apps/omg_eth/test/support/dev_helpers.ex
the `prepare_env` step was frequently run from `apps/omg_eth` dir, which wouldn't work
> docs: improve the explanations to build the dev environment

- apps/omg_watcher/lib/web.ex
- apps/omg_watcher/lib/web/sockets/endpoint.ex
- config/config.exs
Example:
```
2018-09-07 12:59:38.562 [debug] module=Plug.Logger function=call/2 request_id=2l91i3ue8cgh9m2afo000iu3 ⋅GET /status⋅
2018-09-07 12:59:38.564 [debug] module=Phoenix.Logger function=phoenix_controller_call/3 request_id=2l91i3ue8cgh9m2afo000iu3 ⋅Processing with OMG.Watcher.Web.Controller.Status.get_status/2
Parameters: %{}
Pipelines: [:api]⋅
2018-09-07 12:59:38.568 [debug] module=Plug.Logger function=call/2 request_id=2l91i3ue8cgh9m2afo000iu3 ⋅Sent 200 in 5ms⋅
```
> OMG-238 - Logging of wallet provider api request-responses

- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/test/block_getter/core_test.exs
it used to rely on the persisted getter eth height which could remain un-updated
to quickly fix changed that to take persisted child block number into account
> fix: figure out getter synced eth height based on persisted child blknum

- README.md
- docs/install.md
- changed developer's geth command to allow for remote interaction with Geth ie. through a truffle console, geth console or remix
- added the file path to the new vagrant file
> changed developer geth command and vagrant file path

- docs/tesuji_tx_integration.md
Adding an integration specification around generating transaction through to the childchain API. supposedly generalized enough so that implementation could be done agnostic to the programming language
> added transaction integration specification

- README.md
- docs/tesuji_blockchain_design.md
- docs/tesuji_tx_integration.md
Fixing error in docs: signedTxBytes is not a part of RLP encoded signed transaction - it can always be recreated, if needed.
> Docs: signedTxBytes is not a part of RLP encoded signed transaction

- apps/omg_eth/test/support/dev_helpers.ex
Geth does not allow empty passphrase on the testnet. Change it to non-empty one.
Temporary change. Do not merge into dev / master! Normally, use your own script to deploy contract and configure chain on the testnet.
@jbunce
> Change DevHelpers passphrase

- apps/omg_watcher/lib/db/repo.ex
- apps/omg_watcher/lib/db/transaction.ex
Implemented chunking while inserting significant amount of data.
*For instance*
Assuming Pg supports max 65535 parameters  
Each output has 7 fields, so we can bulk insert less than 9362 at once with std `Repo.insert_all/3`
With chunking I was able to insert successfully 11068 transactions (22136 outputs) in one block. 
**Testing whether it works**
Please send **more than 4682 txs per block**, which gives (9364 outputs, 65548 fields).
> add bulk insert chunking support

- apps/omg_api/lib/ethereum_event_listener.ex
- apps/omg_api/lib/ethereum_event_listener/core.ex
- apps/omg_api/lib/root_chain_coordinator/core.ex
- apps/omg_api/test/ethereum_event_listener/core_test.exs
- apps/omg_db/lib/db.ex
By writing to db `current_ethereum_height - maturity_block` and reading value from db as if it was `current_ethereum_height` listener sets itself up for processing of the same events twice. This patch fixes it.
> Prevent event listeners from processing some events twice on restart

- apps/omg_api/lib/ethereum_event_listener.ex
- apps/omg_api/lib/root_chain_coordinator.ex
Returning bad value from handle_info would cause a unneeded coordinator restart.
> bug: botched handle_info clause will cause root_coordinator_restart

- README.md
- apps/omg_db/lib/db.ex
- apps/omg_db/lib/leveldb_server.ex
- apps/omg_db/test/db_test.exs
- LevelDBServer.init won't ever create a leveldb instance
- a database-not-empty error isn't silenced out
- one shouldn't use `mix do` in elixir 1.6 for databases reset (updated README)
Thanks to @kevsul for reporting and tracking
> fix: improve LevelDB init - more verbose and fool proof

- apps/omg_api/mix.exs
- apps/omg_watcher/mix.exs
This is a demo only measure - since there is not enough time to
properly configure :prod mode.
> feat: in :dev setting, stop beam if top-level supervisor dies

- apps/omg_api/lib/root_chain_coordinator.ex
- apps/omg_watcher/lib/db/transaction.ex
- apps/omg_watcher/lib/web/controllers/transaction.ex
- apps/omg_watcher/lib/web/views/transaction.ex
- apps/omg_watcher/test/web/controllers/transaction_test.exs
Transaction endpoint now returns data from block the transaction is included in. The additional info is `eth_height` and `timestamp`
> feature: add timestamp and eth_height to transaction endpoint

- apps/omg_api/lib/root_chain_coordinator.ex
- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
Always use inspect() when interpolating strings in logs
**Critical fix: Broke Watcher**  while testing on mac
CC: @pgebal, @paulperegud
> style: add inspect to value interpolation in logged strings

- apps/omg_api/lib/root_chain_coordinator.ex
- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
please consider whether it doesn't go against your prior assumptions about logging, but without this `info` logs are too verbose to be useful
> fix: clean `info` level logs, suggestion

- apps/omg_watcher/lib/application.ex
- apps/omg_watcher/lib/block_getter/supervisor.ex
This PR amends `Watcher`'s supervision hierarchy and its policy. 
`BlockGetter` and `State` will be allowed to die twice in 3 minutes - the third death kills the whole application.
This PR also includes some formatting alternations.
> fix: restart policies of watcher's submodules

- apps/omg_api/lib/application.ex
- apps/omg_performance/lib/performance.ex
- apps/omg_watcher/lib/application.ex
- apps/omg_watcher/lib/block_getter/supervisor.ex
- apps/omg_watcher/test/fixtures.exs
As of `Elixir 1.5` module `Supervisor.Spec` has been marked as deprecated, so the changes in this PR remove usages of `Supervisor.Spec` and use the new notation instead.
> chore: remove usages of `Supervisor.Spec`

- apps/omg_api/lib/application.ex
- apps/omg_api/test/root_chain_coordinator/core_test.exs
- apps/omg_api/test/state/prop_test.exs
- apps/omg_watcher/test/web/controllers/account_test.exs
- renamed all occurrence of `depositer` to `depositor`
- removed test non-determinism by ensuring sequence order
> remove test flakiness (sequence of returend elements)

- docs/morevp.md
> fix: \neg → \neq in the definition of competing

- mix.lock
No more of this:
```Elixir
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
/home/pawel/omise/chain/deps/exexec/mix.exs:27
```
> fix warning about "coveralls" atom

- apps/omg_eth/config/config.exs
- apps/omg_performance/lib/performance.ex
```
elixir-user@706e6d918044:~/elixir-omg$ mix xomg.child_chain.start --config ~/config.exs
2018-12-07 08:28:58.870 [info] module=OMG.RPC.Application function=start/2 ⋅Started application OMG.RPC.Application⋅
2018-12-07 08:28:58.965 [info] module=Phoenix.Endpoint.CowboyHandler function=start_link/3 ⋅Running OMG.RPC.Web.Endpoint with Cowboy using http://0.0.0.0:9656⋅
2018-12-07 08:28:58.990 [info] module=OMG.API.Application function=start/2 ⋅Started application OMG.API.Application⋅
2018-12-07 08:28:59.024 [info] module=OMG.DB function=utxos/1 ⋅Reading UTXO set, this might take a while. Allowing 600000 ms⋅
2018-12-07 08:28:59.039 [info] module=OMG.API.State function=init/1 ⋅Started State, height: 0, deposit height: 0⋅
2018-12-07 08:28:59.210 [info] module=OMG.API.BlockQueue.Server …
```
> [elixir-omg] Add support for getting Ethereum RPC address from an ENV

- apps/omg_api/lib/block_queue/core.ex
Small improvement in `:debug` logging to tell us why the child chain would refuse to submit blocks.
> feat: be more verbose about skipping form_block and its reasons

- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/lib/db/txoutput.ex
- apps/omg_watcher/test/block_getter/core_test.exs
* speed ups updates (avoid fetch_then_update)
* fetching last_persisted_block_number from DB only on init
> Optimization in WatcherDB

- Jenkinsfile
- README.md
- apps/omg_api/coveralls.json
- apps/omg_rpc/mix.exs
- apps/omg_watcher/coveralls.json
- coveralls.json
- mix.exs
- mix.lock
use 0.10.3 - it already has the fixed that was done in the previous source (github branch) + it additionally fixes the `.html` command, which we use a lot
> fix: update excoveralls dep to fix html output

- apps/omg_api/test/integration/happy_path_test.exs
otherwise, `token_tx` could end up arriving after server is brought down.
resulted in failed assertion on line 108 (pre-diff)
> test: fix race condition in happy_path_test

- .gitignore
- Dockerfile
- Jenkinsfile
- Jenkinsfile.cron
- README.md
- apps/omg_eth/lib/eth.ex
- apps/omg_eth/mix.exs
- apps/omg_eth/test/support/dev_helpers.ex
- contracts/.flake8
- contracts/requirements-to-freeze.txt
- contracts/requirements.txt
- docs/install.md
- docs/troubleshooting.md
Reason to do this is that contract build customization (e.g. libraries) would be awkward otherwise.
This also smuggles a modification (wrt to paramteres in `py-solc-simple`), to have `--optimizer-runs=1` instead of `10000` which tends to give much more expensive deployments (too expensive). About 10% gas is saved (tried on `v0.0` contract code).
Doing `--optimizer-runs=something_flexible` would be hard with `py-solc/-simple`. Drawback is that build systems of `elixir-omg` and `plasma-contracts` diverge, but no biggie, the differences were present elsewhere anyway.
This manages to remove `python` dependency on greater scale (`builder.py` has its own flow)
> OMG-355 use solc to do contract compilation (and reduce deployment gas)

- apps/omg_api/lib/application.ex
- apps/omg_watcher/test/integration/block_getter_test.exs
- docs/exit_validation.md
Child chain's `:exiter`'s finality margin cannot be zero - it must be greater than its `deposit finality margin`. Otherwise there's an option of child chain letting a UTXO be spent that had been exited immediately after the deposit (because deposit's wait and must wait). Such exit processed by `:exiter` would be a noop.
So `:exiter` must wait at least whatever `:depositor` is waiting, to always come after it.
> fix: prevent child chain allowing spends from exiting deposit

- Jenkinsfile
- apps/omg_rpc/lib/web/controllers/block.ex
- apps/omg_rpc/lib/web/controllers/transaction.ex
when we did @api_module.call_sth that would cause compiler to complain, in case @api_module wasn't compiled yet (e.g. on CircleCI)
> fix cleanbuild by making call to OMG.API dynamic

- apps/omg_watcher/lib/exit_processor.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
They used to excite :invalid (and :unchallenged) exit events, because RootChainCoordinator doesn't stop exit processing since  060123a60f6c3739f9b6b391b3f58e7e9a940b21
> OMG-365 handle exits from future utxos when syncing

- apps/omg_watcher/lib/web/sockets/endpoint.ex
- dialyzer.ignore-warnings
Exceptions from the Watcher are not getting caught by Sentry. Phoenix applications require this statement to be added. https://hexdocs.pm/sentry/Sentry.Phoenix.Endpoint.html
> fix: Add Sentry to Watcher's Phoenix endpoint

- launcher.py
This is required for deployment of different contracts for testing in different environments. Default values are used for `os.getenviron.get()` to ensure staging continues to run during staging v2 build.
> feat: Allow contract details for config.exs to be set via an ENV

- apps/omg_api/test/state/core_test.exs
- apps/omg_api/test/state/persistence_test.exs
- apps/omg_db/lib/db.ex
- apps/omg_db/mix.exs
- apps/omg_db/test/db_test.exs
- apps/omg_db/test/support/db_case.ex
Instead of doing a lot of `db_updates` assertions lets run them through the persistence layer (using public APIs) and see if it works as intended.
Reduces the "reaching-into-the-guts" feeling with all the `{:put, :utxo...` etc assertions.
Now persistence per-se is tested in `State.PersistenceTest` and what is left in `State.CoreTest` is more oriented towards various details of the behavior (like flushing the mempool etc.).
Also - battle testing the approach before attacking `ExitProcessor.CoreTest` in a similar manner
> test: enrich and unbrittle Persistence tests of State.Core

- apps/omg_api/lib/crypto.ex
- apps/omg_api/lib/state/transaction.ex
- apps/omg_api/test/crypto_test.exs
- apps/omg_api/test/integration/happy_path_test.exs
- apps/omg_api/test/state/transaction_test.exs
- apps/omg_api/test/support/crypto.ex
- apps/omg_api/test/support/test_helper.ex
- apps/omg_performance/lib/sender_server.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
- docs/demo_01.md
- docs/demo_02.md
- docs/demo_03.md
- docs/demo_04.md
I've stumbled upon a TODO and decided to just fix it for good.
This makes sure that no-one ever is tempted to use private keys in `:prod`.
> refactor: move all private-key related Crypto to DevCrypto

- apps/omg_eth/mix.exs
- apps/omg_watcher/lib/api/status.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
- apps/omg_watcher/test/integration/in_flight_exit_test.exs
This catches up with the Watcher API specs designed by providing an exhaustive list of open IFEs with all the current piggybackings and eth height etc.
Some tests in `ExitProcessor.Core` have been further stripped down (especially persistence, awaiting developments from OMG-329 to test persistence more thoroughly)
> feat: return the list of open IFEs in status

- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/test/block_getter/core_test.exs
workaround for #430 
instead of stopping of the syncing, when an unchallenged_exit is spotted we give a softer warnings
w/ some tests to unskip and remove after OMG_405 (#430) is truly done
> OMG-405 fix: workaround by removing optional & broken stop on unchallenged_exit

- apps/omg_api/config/config.exs
- apps/omg_api/config/dev.exs
- apps/omg_api/config/test.exs
- apps/omg_api/lib/block_queue.ex
- apps/omg_api/lib/ethereum_event_listener.ex
- apps/omg_api/lib/root_chain_coordinator.ex
- apps/omg_api/mix.exs
- apps/omg_api/test/support/integration/deposit_helper.ex
- apps/omg_watcher/config/config.exs
- apps/omg_watcher/config/dev.exs
- apps/omg_watcher/config/prod.exs
- apps/omg_watcher/config/test.exs
- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/lib/db/transaction.ex
- apps/omg_watcher/mix.exs
- apps/omg_watcher/test/support/integration/test_helper.ex
This mainly consists in fixing `:dev` environment, which our deployments use in a way, that allows them to be more robust, under e.g. invalid exits.
Also significant cleanups to config vars and prettify info level logs a bit
> OMG-239 fix: adjust multiple configuration parameters to match Ari/staging needs

- .circleci/config.yml
Replaces sleep statements by checking the childchain pod returns the "Running" status from Kubernetes.
> Fix: Do not deploy the Watcher until the Childchain is in a "Running" status

- apps/omg_watcher/lib/db/eth_event.ex
- apps/omg_watcher/test/db/eth_event_test.exs
First attempt was to create a [Rule On Insert](https://www.postgresql.org/docs/9.1/rules-update.html) but I gave up the idea since EthEvent has association to TxOutput, so there are in fact 2 DB operations.
Idempotent writes is done by simply checking whether record exists in db before write.
There won't be raise condition since deposits/exits are processed sequentially by single process.
I also rejected `Repo.insert_or_update` as it requires fetch the record from DB first, so there will be no gain. 
Closes: #454
> Idempotent writes of deposits and exits to WatcherDB (postgres)

- apps/omg_rpc/config/config.exs
- apps/omg_watcher/config/config.exs
- config/config.exs
Instrumenters configuration needs to be on the Phoenix level, hope that solves it.
https://hexdocs.pm/appsignal/Appsignal.Phoenix.Instrumenter.html
The default value for active seems to be false.
Hope this makes metrics appear in Appsignal.
> fix: make appsignal report metrics

- apps/omg_status/.gitignore
- apps/omg_status/README.md
- apps/omg_status/config/config.exs
- apps/omg_status/lib/status.ex
- apps/omg_status/lib/status/metric/recorder.ex
- apps/omg_status/mix.exs
- apps/omg_status/test/test_helper.exs
An example dashboard for the current metrics.
```
-
title: 'VM dashboard'
graphs:
-
title: 'VM atom over time'
kind: gauge
format: number
draw_null_as_zero: true
fields:
- erlang_system_info_atom_count
tags:
node: '*'
-
title: 'ETS count'
kind: gauge
draw_null_as_zero: false
fields:
- erlang_ets_count
tags:
node: '*'
-
title: 'IO Input KB'
kind: gauge
draw_null_as_zero: false
fields:
- erlang_io_input_kb
tags:
node: '*'        
-
title: 'IO Output KB'
kind: gauge
format: number
draw_null_as_zero: true
fields:
- erlang_io_output_kb
tags:
node: '*'        
-
title: 'Port count'
kind: gauge
draw_null_as_zero: false
fields:
- erlang_system_info_port_count
tags:
node: '*'        
-
title: 'Process count'
kind: gauge
format: number
draw_null_as_zero: true
fields:
- …
```
> feature: gather VM metrics and forward to AppSignal

- apps/omg_api/test/integration/fixtures.exs
- apps/omg_api/test/support/integration/deposit_helper.ex
- apps/omg_eth/lib/eth/defaults.ex
- apps/omg_eth/lib/eth/root_chain.ex
- apps/omg_eth/lib/eth/token.ex
- docs/demo_01.md
- docs/demo_02.md
- docs/demo_04.md
A small patch fixing some stuff that made using our Eth helpers hard on Rinkeby, where Eth isn't that abundant as in `geth --dev`.
Mainly, all our `Eth.Contract.do_sth` calls have a reasonable gas default, instead of `lots_of_gas`
> fix: fix demos, make default gas/gasprice more affordable in OMG.Eth

- apps/omg_api/mix.exs
- apps/omg_status/config/config.exs
- apps/omg_status/config/dev.exs
- apps/omg_status/config/prod.exs
- apps/omg_status/config/test.exs
- apps/omg_status/lib/status.ex
- apps/omg_watcher/mix.exs
Without this, they're not started in deployment.
> fix: omg watcher and api should have status as a umbrella dependency

- apps/omg_api/lib/state/core.ex
- apps/omg_api/lib/sup.ex
- apps/omg_api/test/block_queue/core_test.exs
- apps/omg_api/test/state/core_test.exs
- apps/omg_eth/lib/eth/root_chain.ex
- apps/omg_watcher/lib/db/eth_event.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/lib/supervisor.ex
- apps/omg_watcher/test/db/eth_event_test.exs
- apps/omg_watcher/test/exit_processor/core_test.exs
- apps/omg_watcher/test/exit_processor/persistence_test.exs
otherwise, when a `ExitProcessor.Core.new_exits/2` is called, when an exit already had been challenged,
there's a failed attempt to decode a `Utxo.Position.decode(0)`
The reason is that the "current" contract state of the exit already is wiped clean.
Instead, to limit the fix to the Watcher we take the necessary details of an exit from the relevant `call_data`
> fix: allow processing exits when they were immediately challenged

- apps/omg_api/lib/application.ex
- apps/omg_watcher/lib/supervisor.ex
When Eth client goes out of reach for a period of time, we're not able to recover in time. This increases the amount of restarts that should hopefully allow us to recover the processes.
> fix: increase the amount of restarts per max_seconds

- apps/omg_watcher/lib/exit_processor.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
one clause of `ensure_challengeable` mistakingly accepted `%TransactionSigned` instead of `%KnownTx`.
This solves that + adds tests to cover
refactored a bit for a saner implementation of this
> fix: allow the challenge of SE be made by an IFE transaction

- apps/omg_api/lib/sup.ex
- apps/omg_eth/config/config.exs
- apps/omg_eth/lib/eth.ex
- apps/omg_eth/test/eth_test.exs
- apps/omg_eth/test/fixtures.exs
- apps/omg_eth/test/support/dev_helpers.ex
- apps/omg_eth/test/support/dev_mining_helper.ex
- apps/omg_eth/test/support/dev_node.ex
- apps/omg_eth/test/support/dev_parity.ex
- apps/omg_performance/config/dev.exs
- apps/omg_rpc/test/fixtures.exs
- apps/omg_watcher/lib/application.ex
- docs/install.md
- docs/manual_service_startup.md
Status.
* support for parity quirks
* docs
Integration test fail if run with parity because of postgres sandbox leaking changes to database, compromising isolation between tests. Wrappers tests work fine though.
> Add support for Parity

- apps/omg_rpc/config/dev.exs
- apps/omg_watcher/config/dev.exs
- docs/manual_service_startup.md
before that customizing these ports in `dev` environment required one to override the whole Endpoint config in ~/config.exs,
which is impossible due to the way configs work in Elixir (in case of ~/config.exs it is **not** deeply merged)
fixes #451
> OMG-413 fix: enable PORT env variable for :dev environment + update docs

- apps/omg_watcher/mix.exs
Adds sasl to application list so that alarms can be installed.
> fix: start sasl for alarms

- apps/omg_api/lib/block_queue/core.ex
When complaining about duplicated transactions Parity uses different error code and different message. This PR handles that.
> feat: parity rpc specific errors

- apps/omg/lib/block.ex
- apps/omg/lib/state/core.ex
- apps/omg/lib/utxo.ex
- apps/omg/test/state/core_test.exs
- apps/omg/test/state/persistence_test.exs
- apps/omg_api/lib/fresh_blocks/core.ex
- apps/omg_api/test/fresh_blocks_test.exs
- apps/omg_watcher/lib/exit_processor.ex
- apps/omg_watcher/lib/exit_processor/competitor_info.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex
- docs/demo_01.md
- docs/demo_02.md
- docs/demo_03.md
- docs/demo_04.md
a continuation of #464 movement, which turned out to be necessary for Blocks and Utxo values too
> fix: protecting OMG.DB from refactors in OMG.Block

- apps/omg_watcher/lib/utxo_selection.ex
- apps/omg_watcher/lib/web/controllers/fallback.ex
- apps/omg_watcher/test/web/controllers/transaction_test.exs
- docs/api_specs/errors.md
Handles the case for `/transaction.create` endpoint when request is valid but resulting transaction transfers no funds. This means that both payments was empty and zero-fee was set.
__Explaination__
Empty payments is allowed along with non-zero fee which is funds burning that benefits the operator
__Reviewer__
@pgebal
> [Omg 442] transaction.create: making empty transaction incorrect

- apps/omg/lib/root_chain_coordinator.ex
This removes the node_ready check introduced in #472. The similar check from EthereumEventListener got removed in #519
> fix: allow dual-syncs of geth and watcher

- apps/omg_db/lib/omg_db/leveldb_server.ex
- apps/omg_db/lib/omg_db/recorder.ex
- apps/omg_db/test/omg_db/recorder_test.exs
- apps/omg_status/config/config.exs
- apps/omg_status/lib/omg_status/application.ex
- apps/omg_status/lib/omg_status/metric/recorder.ex
- apps/omg_status/mix.exs
- config/config.exs
- mix.exs
- mix.lock
This is now the complete VM overview. 
I've added :vm_stats dependency which I've vetted myself. It's written and maintained by Fred Hebert, @mononcqc. It has no other dependencies - because it's just calling VM modules and does the necessary grouping. It works by simply enforcing a behavior  which we need to implement and send off to AppSignal.
I've also rewritten the plotting part. It now makes more sense :D
```
title: VM dashboard
graphs:
- title: 'Writes, reads and multireads - LevelDB in interval'
line_label: '%node%'
format: number
draw_null_as_zero: true
metrics:
- name: leveldb_write
fields:
- COUNTER
tags:
node: '*'
- name: leveldb_read
fields:
- COUNTER
tags:
node: '*'
- name: leveldb_multiread
fields:
- COUNTER
tags:
node: '*'
- title: vmstats$.scheduler_wall_time$.1.total - …
```
> OMG-218 refactor: vm stats

- apps/omg/lib/omg/root_chain_coordinator.ex
- apps/omg/lib/omg/state.ex
- apps/omg_api/lib/omg_api/alert/alarm_handler.ex
- apps/omg_api/lib/omg_api/ethereum_client_monitor.ex
- apps/omg_api/lib/omg_api/monitor.ex
- apps/omg_api/lib/omg_api/sup.ex
- apps/omg_api/test/omg_api/ethereum_client_monitor_test.exs
- apps/omg_api/test/omg_api/integration/monitor_test.exs
- apps/omg_watcher/lib/omg_watcher/alert/alarm_handler.ex
- apps/omg_watcher/lib/omg_watcher/application.ex
- apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
- Because of the pub/sub to alarms I was able to remove all the timers in monitoring and by that, simplified the implementation and testing a lot (there's no race conditions anymore), and ethereum client monitor now doesn't constantly publish it's cleared or raised events.
- I've also made these two modules parametrized so that they are usable from both childchain and watcher. 
- The supervision tree `OMG.Watcher.BlockGetter.Supervisor` was removed and all his children moved one level up. They're all eth client dependent and we're handling them in the custom monitor.
> fix: alarms raised in the appropriate application and passed as param, removed supervision tree

- apps/omg/lib/omg/state.ex
- apps/omg/lib/omg/state/core.ex
- apps/omg/test/omg/state/core_test.exs
- apps/omg/test/omg/state/persistence_test.exs
- apps/omg/test/omg/state_test.exs
- apps/omg_api/lib/omg_api/sup.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
The functionality to emit the stub of `ExitFinalized` events got placed in `State` following the example of transaction events. But exit finalized don't seem to have a good reason to not be emitted from the `ExitProcessor` for much cleaner code.
Also, fixed a broken test in `ExitProcessor`: [here](https://github.com/omisego/elixir-omg/compare/emit_exit_finalized_from_exit_processor?expand=1#diff-91398068aa8ecf8b7913c807e662c304R344) one should be testing processing of valid exits, as the test title suggests.
> refactor: move emitting exit_finalized events to ExitProcessor

- apps/omg_watcher/lib/omg_watcher/web/channels/exit.ex
- apps/omg_watcher/lib/omg_watcher/web/channels/transfer.ex
without this, the log level being `:info` for `join` events we were getting a flood of:
```
2019-04-03 14:16:52.350 [info] module=Phoenix.Logger function=phoenix_socket_connect/3 ⋅CONNECT OMG.Watcher.Web.Socket
```
> fix: silence channel join logs

- README.md
- apps/omg/config/config.exs
- apps/omg/mix.exs
- apps/omg_api/config/config.exs
- apps/omg_api/mix.exs
- apps/omg_db/config/config.exs
- apps/omg_db/mix.exs
- apps/omg_eth/config/config.exs
- apps/omg_eth/mix.exs
- apps/omg_watcher/config/config.exs
- apps/omg_watcher/lib/omg_watcher/web/endpoint.ex
- apps/omg_watcher/mix.exs
Turns out, we don't need to put all the config entries twice, the entries in `mix.exs` were redundant, contrary to how Mix docs were understood.
This PR puts all the config entries into `config/config.exs` files of the respective apps
Also, exhaustive documentation about the entries was added, per an old suggestion from @pthomalla :+1:
fixes #560
> refactor: put all mix config entries in `config.exs` files, document

- apps/omg_watcher/lib/web/sockets/socket.ex
follow up to #577. Gets rid of 
```
2019-04-05 12:27:43.859 [info] module=Phoenix.Logger function=phoenix_socket_connect/3 ⋅CONNECT OMG.Watcher.Web.Socket
Transport: :websocket
Connect Info: %{}
Parameters: %{"vsn" => "2.0.0"}⋅
2019-04-05 12:27:43.859 [info] module=Phoenix.Socket function=log_connect_result/3 ⋅Replied OMG.Watcher.Web.Socket :ok⋅
```
> fix: silence the Phoenix.Socket connect logs to debug too

- launcher.py
Currently `docker-compose` on linux returns
`ecto.migrate": 1 error found!\n--no-start : Unknown option`
I removed the `--no-start` args and watcher started working again
> removed --no-start

- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/web/controllers/in_flight_exit_test.exs
port of #592 from `v0.1` to `master`.
> fix: handle malformed txbytes as inputs to IFE-related endpoints

- apps/omg_watcher/lib/db/transaction.ex
- apps/omg_watcher/lib/db/txoutput.ex
- apps/omg_watcher/priv/repo/migrations/20190408131000_add_missing_indices_to_txoutputs.exs
- apps/omg_watcher/test/db/transaction_test.exs
- docker-compose-non-mac.yml
- docker-compose.yml
closes #589
This PR switches from using a double left join to using a single inner with a bunch of added indices for increased performance. 
Also cherry picked [this commit](https://github.com/omisego/elixir-omg/commit/946197ccb372b9be6971abe6587d133e777a63a4) to get it into 0.1 (it was preventing Docker from starting).
> Fix /transaction.all slow responses

- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/request.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
Partially covers #608.
This PR focuses on drying `exit_processor.exs` code, especially the interactions with the data storage.
Also some readability improvements.
Probably reviewing commit-by-commit (and final state) is recommended
> tidy exit processor pt1 - `ExitProcessor`

- apps/omg/lib/omg/utxo/position.ex
- apps/omg_watcher/lib/omg_watcher/db/txoutput.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/request.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit_challenge.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core/standard_exit_challenge_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
The section of the ExitProcessor to handle standard exit challenges became very messy.
Now handling is pipelined and testable, as in IFE handling.
New tests were added, thanks to the improved testability.
As a bonus - the SE-challenge functionality & tests have their own files/modules now
Covers part of #608
> refactor: rewrite SE challenges, add tests

- apps/omg_watcher/lib/web/router.ex
- apps/omg_watcher/test/support/test_helper.ex
- apps/omg_watcher/test/web/controllers/status_test.exs
closes #601 ~~(@pnowosie: I'd keep the issue to clean implementation, but not hold this PR open)~~ 
This PR removes the `Content-Type` requirement for the `/status.get` endpoint. The solution implemented in this PR is __not optimal__ and just a quick fix. The content-type / body parsing should be left to Phoenix instead of being done inside a custom plug function.
> Remove content-type requirement for /status.get

- apps/omg/lib/omg/block.ex
- apps/omg/mix.exs
- apps/omg/test/fixtures.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/core/standard_exit_challenge_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
- apps/omg_watcher/test/support/exit_processor/test_helper.ex
- mix.lock
Continuing work towards #608 
This PR aims at DRYing, splitting up (a bit) and simplifying the tests of `ExitProcessor.Core`.
Use of `fixtures` has been greatly reduced. Firstly, there's a lot less reliance on shared fixtures between tests, so that modifying the fixture to add a more specific test isn't necessary - one can now much more easily setup the new tests using helper functions etc. The "rich" fixtures like `processor_filled` are intended to be used whenever we can take them "as they are" and rely only on the generic setup they contain.
This effort can be continued. Things left to do:
- divide up the large remaining test into `describe` blocks or separate test files, to make the setup more focused and readable. The way this test is arranged should be thought through carefully
- …
> tidy exit processor pt3 - `ExitProcessor.CoreTest`

- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
Fixes the situation which looks like the following:
```
2019-04-25 11:45:53.709 [error] module=gen_server function=error_info/7 ⋅GenServer OMG.Watcher.ExitProcessor terminating
** (FunctionClauseError) no function clause matching in OMG.Watcher.ExitProcessor.Core.get_known_txs/1
(omg_watcher) lib/exit_processor/core.ex:738: OMG.Watcher.ExitProcessor.Core.get_known_txs([:not_found])
(omg_watcher) lib/exit_processor/core.ex:523: OMG.Watcher.ExitProcessor.Core.get_ifes_with_competitors/2
(omg_watcher) lib/exit_processor/core.ex:487: OMG.Watcher.ExitProcessor.Core.invalid_exits/2
(omg_watcher) lib/exit_processor.ex:257: OMG.Watcher.ExitProcessor.handle_call/3
(stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
(stdlib) gen_server.erl:690: :gen_server.handle_msg/6
(stdlib) …
```
> fix: make ExitProcessor tolerate spending blocks not being found

- apps/omg_eth/test/support/dev_helpers.ex
Issue raised by @jbunce - cannot deploy contract because of insufficient funds.
After this changes it tries first to get faucet address as deployer and fallbacks to first address if not provided.
> Deploying with faucet addres instead of first

- launcher.py
Kubernetes only accepts pod names in characters from the English alphabet:
```
Invalid value: "GÖRLI_CONTRACT_ADDRESS": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')
```
> fix: GÖRLI -> GORLI

- .circleci/config.yml
- apps/omg/config/config.exs
- apps/omg/config/test.exs
- apps/omg/lib/omg/ethereum_client_monitor.ex
- apps/omg/lib/omg/state/transaction/signed.ex
- apps/omg/test/omg/crypto_test.exs
- apps/omg/test/omg/ethereum_client_monitor_test.exs
- apps/omg/test/omg/integration/root_chain_coordinator_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/happy_path_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/monitor_test.exs
- apps/omg_db/test/omg_db/application_test.exs
- apps/omg_db/test/omg_db/db_test.exs
- apps/omg_eth/test/omg_eth/eth_test.exs
- apps/omg_performance/test/omg_performance/integration/performance_test.exs
- apps/omg_status/test/omg_status/integration/alarms_test.exs
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/test/omg_watcher/integration/block_getter_test.exs
- apps/omg_watcher/test/omg_watcher/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/omg_watcher/integration/invalid_exit_test.exs
- apps/omg_watcher/test/omg_watcher/integration/standard_exit_test.exs
- apps/omg_watcher/test/omg_watcher/web/controllers/status_test.exs
I've seen that integration tests can take around 20 minutes now so I thought it might be a good time to try and reduce the time.
I've split the integration + wrapper tags into child chain, watcher and common (everything else) and we run them in parallel, gather the results and send off to coveralls. It reduces the runs significantly. Also, we now compile the source only once, cache the _build folder just before the test run.
> feature: parallel coveralls

- apps/omg_watcher/lib/omg_watcher/web/endpoint.ex
- docs/api_specs/watcher_websocket_specs.md
I wasted some time on this, the docs on this are a bit concealed in `Phoenix.Channels` or just my bad luck. Deciding to leave some docs on our side as well
> docs: clarify the confusing bit about socket route for watcher channels

- .circleci/config.yml
Master is currently failing https://circleci.com/gh/omisego/elixir-omg/6765 because of missing cmake (it's used to compile rocksdb -> https://gitlab.com/barrel-db/erlang-rocksdb#usage ).
> apt install cmake

- README.md
The current link for the operator api spec is wrong: https://developer.omisego.co/elixir-omg/docs-ui/?url=0.1/operator_api_swagger.yaml
This PR updates it to point to: https://developer.omisego.co/elixir-omg/docs-ui/?url=0.1/operator_api_specs.yaml
> Fix wrong filename for 0.1 operator api spec

- apps/omg/lib/omg/state/core.ex
- apps/omg/test/omg/state/core_test.exs
- apps/omg_eth/lib/omg_eth/root_chain.ex
- apps/omg_eth/mix.exs
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
- apps/omg_watcher/test/omg_watcher/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/support/exit_processor/test_helper.ex
Partly solves #630. Exited utxo can no longer be spent, but IFEs are not reflected in convenience API. That will be solved in a separate PR.
Closes #630.
> fix: finalize in-flight exits in Watcher

- apps/omg_api/lib/block_queue.ex
- apps/omg_api/lib/block_queue/core.ex
- apps/omg_eth/test/support/dev_geth.ex
Covers two common situations:
- when BlockQueue can't start because the `OMG.DB` mismatches with the contract
- when BlockQueue can't submit blocks because the authority address is locked
When this happens we'll going to be building some relevant diagnostic data and including it in the error log.
Should help with issues like #662
> feat: improve error logs when BlockQueue has problems

- README.md
- apps/omg_db/config/config.exs
- apps/omg_db/lib/omg_db/level_db.ex
- apps/omg_db/lib/omg_db/leveldb/server.ex
- apps/omg_db/lib/omg_db/release_tasks/init_key_value_db.ex
- apps/omg_db/lib/omg_db/release_tasks/set_key_value_db.ex
- apps/omg_db/lib/omg_db/rocks_db.ex
- apps/omg_db/lib/omg_db/rocksdb/core.ex
- apps/omg_db/lib/omg_db/rocksdb/server.ex
- apps/omg_db/test/fixtures.exs
- apps/omg_performance/lib/performance.ex
- apps/omg_watcher/test/fixtures.exs
- docs/manual_service_startup.md
- launcher.py
This addresses some of the configuration issues of using two databases with same configuration and sorts out the key prefixes used for iterator scans.
Also adds same measurements as we have for LDB.
> refactor: prefix and configuration cleanup

- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/competitor_info.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/exit_info.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit_challenge.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/tools.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core/standard_exit_challenge_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
references #608
Solves multiple issues with `ExitProcessor.Core`:
- dries consumption of ethereum events
- dries and clarifies the flows related to piggyback invalidity checks
- adds some tests (changes to `core_test.exs` are only additive or cleanups)
- separates some code into submodules
- dries the double spend functionality which was implemented three-fold (for competitors, for piggybacks and for ife-se cross checks)
- makes handling of piggyback indices (with either the magical "4" added or not) cleaner - now "4" is added only on the "outside". Inside of `ExitProcessor.Core` "natural" indices are used + an explicit indication whether `input` or `output` is meant, as necessary
> Refactor ExitProcessor.Core (tidy exit processor pt4)

- apps/omg_watcher/lib/supervisor.ex
- apps/omg_watcher/test/supervisor_test.exs
fixes #695
The problem noted was that a transaction managed to slip through and be processed on the WatcherDB end before a deposit.
Now we explicitly make the `BlockGetter` service wait for `convenience_deposit_processor`.
> fix: make deposits written to WatcherDB always come before getter's txs

- apps/omg_watcher/lib/block_getter.ex
Fixes #703.
Otherwise, on invalid blocks BlockGetter will merily continue bumping its  synced height. An invalid block event might never reappear in logs, even on restarts
> fix: make BlockGetter take a not-ok-chain into account when syncing

- apps/omg/lib/omg/ethereum_event_listener.ex
- apps/omg/lib/omg/root_chain_coordinator.ex
- apps/omg/lib/omg/root_chain_coordinator/core.ex
- apps/omg/test/omg/root_chain_coordinator/core_test.exs
- apps/omg_child_chain/lib/omg_child_chain/block_queue.ex
- apps/omg_eth/lib/eth.ex
- apps/omg_eth/lib/omg_eth/application.ex
- apps/omg_eth/lib/omg_eth/diagnostics.ex
- apps/omg_eth/mix.exs
- apps/omg_eth/test/omg_eth/eth_test.exs
- apps/omg_watcher/lib/omg_watcher/api/status.ex
- apps/omg_watcher/lib/omg_watcher/block_getter.ex
- apps/omg_watcher/lib/omg_watcher/coordinator_setup.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/web/views/status.ex
- apps/omg_watcher/priv/swagger/watcher_api_specs.yaml
- apps/omg_watcher/test/omg_watcher/supervisor_test.exs
- apps/omg_watcher/test/omg_watcher/web/controllers/status_test.exs
- mix.lock
On a couple of occasions we wished `status.get` returned richer information about the status the watcher's syncing is in.
Also, such information (like how old is the head of ethereum **as seen by the watcher**) is security-critical information - we're only secure and able to spend and use the child chain if we're fully up-to-date with ethereum.
So this is a proposition to put more stuff into the `status.get` response:
```
iex(30)> ~c(echo '{}' | http POST #{watcher_url}/status.get) |>  :os.cmd() |>  Poison.decode!()
%{
"data" => %{
"byzantine_events" => [],
!! NEW !! ===> "contract_addr" => "0x3c651506beb2ce64806f8fcf03522a211de19133",
"eth_syncing" => false,
"in_flight_exits" => [],
"last_mined_child_block_number" => 1000,
"last_mined_child_block_timestamp" => 1558535130,
!! NEW !! ===> …
```
> feat: return rich syncing information from /status.get

- .circleci/ci_publish.sh
- .circleci/config.yml
- .gitignore
- Dockerfile.child_chain
- Dockerfile.watcher
- Makefile
- apps/omg_child_chain/config/dev.exs
- mix.exs
- rootfs/child_chain_entrypoint
- rootfs/watcher_entrypoint
This is part 1 of work that needs to be done to move our deployment towards OTP releases.
All images are based on Alpine 3.8 - https://github.com/omisego-images/docker-elixir-omg
Integration tests run towards custom alpine with geth and solc. It would be good to move away from this model though.
Processes and flows have been adjusted in a way similar to eWallet... thanks @sirn !!! But with separate repositories so that we're not coupled with their work.
> setup containers with releases

- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
- apps/omg_watcher/test/omg_watcher/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/support/exit_processor/test_helper.ex
There used to be a small deficiency of the IFE canonicity game left behind: the responses to invalid IFE challenges would not be recognized by the Watcher.
Also, the Watcher would tell the user to challenge a (suposedly) non-canonical IFE, even if it was canonical, and the competitors it had **were younger than the IFE tx**.
E.g. when there's tx1, IFEd and included in some block and a competing tx2 IFEd only, we used to report two non-canonical byzantine events, despite the challenge to tx1 doesn't make sense.
After the changes proposed, this is no longer the case. The watcher asseses the sensibility of the canonicity challenge in full extent, i.e. it analyzes the inclusion and age of competitors and only tells to challenge if the tx in question is truly non-canonical (according to …
> Proper ife response handler

- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/tx_appendix.ex
Follow up to #706
fixes an issue found in review of  #706 - known_txs are large and undergo several steps of processing, so using Enum can be very suboptimal
- use `Stream` instead of `Enum` in all the spots where large collections are used in `ExitProcessor` - namely the stream of so-called `known_txs`
- we are less exposed to being hit by a large memory footprint of doing large processing pipelines of large lists using `Enum`.
N/A - code covered by existing unit tests, behaviors stay the same
> fix: use Stream for the large collections of known_txs in ExitProcessor

- Dockerfile
- docker-compose-full-services-mac.yml
- docker-compose-full-services-non-mac.yml
- docker-compose-watcher-mac.yml
- docker-compose-watcher-non-mac.yml
- launcher.py
fixes #691
A number of orthogonal fixes that allow the docker-composed watchers to sync to `samrong`
Now it syncs fine and doesn't complain anything:
```
$ docker-compose -f docker-compose-watcher-non-mac.yml up
...
watcher_1     | 2019-05-29 10:19:05.276 [info] module=OMG.Watcher.BlockGetter function=handle_cast/2 ⋅Applied block: #51000, from eth height: 4460698 with 2 txs⋅
```
- provide correct `samrong` contract addresses etc. in the `docker-compose` YAMLs,  to be able to sync with `master`/`v0.2`
- use `network_mode: host` for the watcher container (but not postgres, otherwise it clashes with the locally run one)
- rearrange `Dockerfile` to not have to reinstall solc/pip installs every time our code changes
- don't have the superfluous `mix ecto.reset` in the `docker-compose` YAMLs …
> fix: fix docker compose to handle DB conn & startup correctly

- apps/omg_db/config/config.exs
- apps/omg_db/lib/db.ex
- apps/omg_db/lib/omg_db/application.ex
Slack.
RocksDB is implemented, but not tested "in the wild".
- Pull the DB type from ENV.
Hey, If it works, it works.
> feature: swap DB type via env

- Dockerfile.watcher
- Makefile
- apps/omg_eth/lib/omg_eth/release_tasks/set_contract.ex
- apps/omg_eth/lib/omg_eth/release_tasks/set_ethereum_client.ex
- apps/omg_watcher/lib/omg_watcher/block_getter/supervisor.ex
- docker-compose-watcher-mac.yml
- docker-compose-watcher-non-mac.yml
- rel/config.exs
- rootfs/child_chain_entrypoint
- rootfs/watcher_entrypoint
#579 
Ha! The local watcher now pulls in a the latest image created from master, tagged as *latest*!
- Getting the proper ethereum client address from env, and setting it in the sys.config via config providers.
- adding a command `full_local` that wipes the DB's every run. Ecto reset and KV wipe.
make docker-watcher && docker-compose -f docker-compose-watcher-mac.yml up
> feature: make local watcher run a proper OTP release

- apps/omg/lib/omg/state.ex
- apps/omg_watcher/lib/omg_watcher/block_getter.ex
:clipboard: Fixes https://github.com/omisego/elixir-omg/issues/724
When Watcher starts for the 2nd time after it's fully sync 
it suffers from BlockGetter.Supervisor children several restart.
BlockGetter waits for the ExitProcessor to start
Feed ch-ch with 1.5M transactions (e.g. for test #723 )
Sync Watcher, stop it
Start Watcher again
> fix: fix starting watcher

- apps/xomg_tasks/lib/mix/tasks/watcher.ex
Slack
Application omg_watcher_rpc must be started manually.
- Instead of the applications bootup tree being resolved it must be specified manually.
/
> because we have a very special bootup :-)

- apps/omg_watcher_rpc/lib/web/router.ex
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/enforce_content_plug_test.exs
- docs/api_specs/errors.md
:clipboard: Fixes #590 
Following HTTP-RPC we required every request specifies header `Content-Type: application/json`. This causes issues with REST clients on paths that passes no data in the body.
Removes header enforcing.
- [apps/omg_watcher/lib/omg_watcher/web/router.ex](https://github.com/omisego/elixir-omg/blob/d4a529836c56d8c1ac70d9d850d8d9737a493a0b/apps/omg_watcher/lib/omg_watcher/web/router.ex)
No need to test - it's HTTP protocol behavior.
> 590 Remove 'Content-Type' header enforcing

- apps/omg_watcher_rpc/lib/web/endpoint.ex
CORS headers missing from response
/
- Fetch settings from proper app
/
> fix: get cors settings from proper app

- docs/install.md
- docs/manual_service_startup.md
:clipboard: https://github.com/omisego/elixir-omg/issues/712
This updates the installation instructions for Linux. Tested on (my) fresh linode.
- Remove Vagrant because I don't think we recommend this anymore
- Add a few missing dependencies
- Specify solidity version `0.4.x` is required (contracts cannot be compiled with `0.5.x` right now)
- Add instructions for installing latest `0.4.x` release manually
- Update PostgreSQL instructions and move to `install.md` from `manual_service_startup.md`
- Add Parity install instructions
- Add `mix deps.compile` (needed for `libsecp256k1-dev`)
> Chore: Update installation instructions for Linux

- .circleci/config.yml
Test runner does not succeed because the Watcher is not yet ready. This bumps the sleep timer. 
sleep 200
Yolo?
> fix: Sleep time increase to allow Watcher to deploy

- .circleci/config.yml
The test-runner fails because the service isn't ready after a deploy. This halts execution of the test-runner until the ingress is live.
`kubectl` -> `curl`
> fix: Change from waiting for k8s readiness to full e2e

- docs/run_local_watcher.md
Howdy
Local watcher run needs Postgres service.
- Manually specify the default docker-compose file because it's not being picked up on 
```
Linux
docker-compose version 1.24.0, build 0aa59064
Mac
docker-compose version 1.23.2, build 1110ad01
```
> fix: Service 'watcher' depends on service 'postgres' which is undefined.

- Dockerfile
- config/config.exs
- mix.exs
:clipboard: #771
:clipboard: https://github.com/omisego/devops/pull/103
This PR is dependent on https://github.com/omisego/devops/pull/103. This leverages `APP_ENV` to pick up our Sentry environment instead of `MIX_ENV`.
* Use `APP_ENV` instead of `MIX_ENV`: 1a3e70a7
* Add additional Sentry tags like `eth_network`, `mix_env`, and `eth_node`
* Remove source code context feature until a later PR. Would make our deploys a bit more difficult at the moment.
```sh
ETH_NODE="bar" ETHEREUM_NETWORK="foo" APP_ENV="prod" MIX_ENV=dev mix sentry.send_test_event
```
> Use `APP_ENV` for Sentry environment

- apps/omg/lib/omg/ethereum_client_monitor.ex
- docker-compose-full-services-mac.yml
- docker-compose-full-services-non-mac.yml
- docs/manual_service_startup.md
:clipboard: Closes #802
Now, instead of pulling eth node Watcher subscribes to `newHeads` event on web socket. When the connection is lost (or node was run without ws) this should be more visible.
Changed log severity about lost connection from `debug` to `warn`
Changed examples in our manuals that explicitly enables ws in `geth`
/
> Eth node streaming api has to be enabled

- apps/omg_status/lib/omg_status/application.ex
- apps/omg_utils/mix.exs
- config/config.exs
- docker-compose-watcher-mac.yml
- docker-compose-watcher-non-mac.yml
- docs/run_local_watcher.md
Statix was not picked up in a dependecy tree when building a release.
Watcher image missing WS env. variables
- ...
> fix: statix not pickedup as dependency app in a release and wss env vars

- apps/omg/config/config.exs
- apps/omg/lib/omg/crypto.ex
- apps/omg/lib/omg/fees.ex
- apps/omg/lib/omg/typed_data_hash/config.ex
- apps/omg/test/omg/crypto_test.exs
- apps/omg/test/omg/dependency_conformance/signature_test.exs
- apps/omg/test/omg/state/transaction_test.exs
- apps/omg/test/omg/typed_data_hash_test.exs
- apps/omg_child_chain/lib/omg_child_chain/block_queue.ex
- apps/omg_eth/lib/omg_eth/defaults.ex
- apps/omg_eth/lib/omg_eth/wait_for.ex
- apps/omg_eth/test/fixtures.exs
- apps/omg_eth/test/support/dev_helpers.ex
- apps/omg_eth/test/support/dev_mining_helper.ex
- apps/omg_eth/test/support/librarian.ex
- apps/omg_eth/test/support/token.ex
- apps/omg_performance/lib/performance.ex
- apps/omg_watcher/lib/omg_watcher/eventer/core.ex
- apps/omg_watcher/test/omg_watcher/eventer/core_test.exs
- apps/omg_watcher/test/omg_watcher/integration/block_getter_test.exs
- apps/omg_watcher/test/omg_watcher/integration/standard_exit_test.exs
- apps/omg_watcher/test/omg_watcher/integration/transaction_submit_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/account_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/validators/typed_data_signed_test.exs
- docs/demo_01.md
- docs/demo_02.md
- docs/demo_03.md
:clipboard: Fixes #816
Unifies usage of Hex encoders
Removed Crypto.(de|en)code_address, limited usage to Eth.Encoding & Utils.HttpRPC.Encoding.
In code try to use Eth.Encoding except the cases RPC is used.
In test use whatever fits (including Base.decode16)
Cleaning work, existing test should suffice.
> Unifies usage of Hex encoders

- apps/omg/lib/omg/alert/alarm.ex
- apps/omg/lib/omg/alert/alarm_handler.ex
- apps/omg/lib/omg/fees.ex
- apps/omg/test/support/test_helper.ex
- apps/omg_child_chain/lib/omg_child_chain/fee_server.ex
- apps/omg_child_chain/test/omg_child_chain/integration/fee_server_test.exs
:clipboard: Fixes #815 
Changes fee file handling to be more forgiving regarding user errors in the file structure.
Expected behavior is:
* if the child chain is starting and fee file is corrupted it should crash
* if the child chain is running and file was updated corrupting it, error message is logged, alarm raised and last valid fees are effective.
* prevented `fee_server` process from crashing on json-serialization issues
* added alarms to raise issues with file parsing.
Added integration test for fee_server that shows the expected behavior.
> fix: change fee_server not to crash on corrupted json

- apps/omg_watcher/test/omg_watcher/integration/block_getter_test.exs
- apps/omg_watcher/test/support/test_helper.ex
Sometimes the log is printed before the capture_log is enabled, and test fails.
```
* test transaction which is using already spent utxo from exit and happened after margin of slow validator(m_sv) causes to emit unchallenged_exit event2019-07-22 10:23:53.074 [warn] module=OMG.Watcher.Application function=set_cookie/1 ⋅Cookie not applied.⋅
2019-07-22 10:24:25.204 [warn] module=OMG.Watcher.BlockGetter.Core function=consider_exits/2 ⋅Chain invalid when taking exits into account, because of {:error, :unchallenged_exit}⋅
2019-07-22 10:24:25.204 [warn] module=OMG.Watcher.BlockGetter function=do_producer/1 ⋅Chain invalid when trying to download blocks, because of {:error, []}, won't try again⋅
* test transaction which is using already spent utxo from exit and happened after margin of slow …
```
> test: fix race in catching log in block_getter_test

- apps/omg/lib/omg/block.ex
- apps/omg/lib/omg/state/transaction/recovered.ex
- apps/omg/lib/omg/state/transaction/signed.ex
- apps/omg/test/support/crypto.ex
- apps/omg_watcher/lib/omg_watcher/db/transaction.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
This is just clean-up, but will be useful for #844 to have it done.
As title. This is much tidier. `signed_tx_bytes` held there is useful only when we're operating on the `Transaction.Recovered` structure. Storing it in `Transaction.Signed` was awkward and confusing
Move `:signed_tx_bytes` filed from `Transaction.Signed` to `Transaction.Recovered`
Everything covered in tests as it was + no modifications to tests necessary :tada:
> refactor: move the signed_tx_bytes entry from Signed to Recovered

- Makefile
- apps/omg_db/lib/omg_db/release_tasks/init_key_value_db.ex
- docker-compose.dev.yml
- docker-compose.yml
Quicker cluster startup with Datadog
Override enivornment variables in docker compose for development and a Makefile entry to ease typing.
^^
/
> fix: start and override config for dev datadog

- .gitignore
- Makefile
- docker-compose.yml
deploying dies
```
plasma-deployer_1  | 15:49:08.921 [info]  2_initial_migration.js
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]  ======================
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]  
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]     Deploying 'Migrations'
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]     ----------------------
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]  Error: Error: Error:  *** Deployment Failed ***
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]  
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]  "Migrations" exceeded the block limit (with a gas value you set).
plasma-deployer_1  | 
plasma-deployer_1  | 15:49:08.921 [info]     * Block …
```
> fix: deploying frequently dies because of insufficient gas

- README.md
- apps/omg_child_chain/config/config.exs
- apps/omg_child_chain/config/test.exs
- apps/omg_child_chain/lib/omg_child_chain/fee_server.ex
-
Lowers the said interval in tests - without this, some glitches in the behavior of the child chain were uncaught (revolving around fee-file-reading and simple perf test)
Unhardcodes the interval. Non `:test` behavior stays the same.
Same tests
> fix: lower the fee_file_check_interval_ms in tests

- coveralls.json
Spotted by @InoMurko
PRovides a top level coveralls.json with exclude dirs - the ones sitting in the umbrella subapps aren't enough for the new `coveralls` task which works from the top-level
N/A
existing testes + :eyes: on the coveralls.io report
> fix: provide a top-level coveralls.json for the new coveralls flow

- CHANGELOG.md
:clipboard: fixes https://github.com/omisego/elixir-omg/issues/800
This adds `v0.1.6`, `v0.2.0`, `v0.2.1` to the CHANGELOG
Generated with:
```
$ CHANGELOG_GITHUB_TOKEN=token make changelog
```
Then:
- Moved `v0.1.6` above `v0.1.5` and below `v0.2.0`
- Removed 'fixed bugs' and 'enhancement' sections
> chore: Add v0.1.6...v0.2.1 to CHANGELOG

- docker-compose-watcher.yml
This PR addresses an issue I encountered when attempting to start the Watcher on it's own via the `docker-compose -f docker-compose-watcher.yml up` command. When attempting to do so, I would consistently get the following error:
```
watcher_1   | Creating database at nil
watcher_1   | ▸  Evaluation failed with: function nil.init_storage/1 is undefined
watcher_1   | ▸      nil.init_storage("/app")
watcher_1   | ▸      (omg_db) lib/omg_db/level_db.ex:138: OMG.DB.LevelDB.do_init/2
watcher_1   | ▸      (omg_db) lib/omg_db/release_tasks/init_key_value_db.ex:37: OMG.DB.ReleaseTasks.InitKeyValueDB.init_kv_db/1
watcher_1   | ▸      (omg_db) lib/omg_db/release_tasks/init_key_value_db.ex:32: OMG.DB.ReleaseTasks.InitKeyValueDB.process/1
watcher_1   | ▸      (omg_db) …
```
> Fix docker-compose-watcher.yml

- Dockerfile.watcher
Follow-up to #904 which broke `master` publishing of images b/c of hard-coded 0.2.0 missed.
-
I'm just doing for `Dockerfile.watcher` what is already done for `child_chain` that works fine.
-
> fix: use release_version in the watcher Dockerfile too, not fixed 0.2.0

- apps/omg_child_chain/lib/child_chain.ex
- apps/omg_child_chain/lib/omg_child_chain/monitor.ex
- apps/omg_child_chain/mix.exs
- apps/omg_child_chain/test/omg_child_chain/child_chain_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/fixtures.exs
- apps/omg_child_chain_rpc/config/config.exs
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/alarm.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/block.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/transaction.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/views/alarm.ex
- apps/omg_child_chain_rpc/mix.exs
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/web/controllers/alarm_test.exs
- apps/omg_child_chain_rpc/test/support/web/test_helper.ex
- apps/omg_performance/lib/performance.ex
- apps/omg_status/lib/omg_status/alert/alarm_handler.ex
- apps/omg_watcher/lib/omg_watcher/monitor.ex
- apps/omg_watcher/test/omg_watcher/api/alarm_test.exs
- apps/omg_watcher/test/omg_watcher/integration/monitor_test.exs
- apps/omg_watcher_rpc/lib/web/controllers/alarm.ex
- docs/architecture.md
///
Read the raised alarms on an Child Chain endpoint _http://child_chain/alarm.get_
- Added a new route!
- Copied tests from Watcher
- Fixed a few other issues
- Decoupled Child Chain from Child Chain RPC so that coupling occurs in the same way as in Watcher. RPC->APP (this allowed me to remove slow dynamic module invocation `apply/3`)
Wrote a few tests that should cover all behaviors.
> feature: expose child chain alarms via alarm.get

- apps/omg_utils/lib/omg_utils/http_rpc/response.ex
Using mix tasks to startup the application (watcher or child chain) all modules are always loaded into the VM. But the application VSN is part of application running which is not. Now development is down.
Check if child chain is running every request... HACK.
> fix: check if child chain is running

- apps/omg_status/lib/omg_status/metric/vmstats_sink.ex
DD support has been rather unhelpful in mitigating our infrastructure->tags->datadog problem. 
Just to move us forwards adding this "hack"
Adding tags to metrics depending on which application is running
- Get the application mode
- Store it in process dictionary
- retrieve it, send it to DD
> fix: set tags programatically

- apps/omg_status/mix.exs
- mix.lock
Tags stopped appearing because https://github.com/lexmag/statix/commit/d1e65cc98a75d22a2d8a36dad41e88ffd802e9ff#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR10
Updated Statix to 1.2
/
> fix: global dd tags comes in 1.2

- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/application.ex
- apps/omg_watcher_rpc/lib/application.ex
Neither child chain or watcher are running when omg status app boots...
- Changes in appropriate applications
/
> fix: set tag per app

- apps/omg_status/lib/omg_status/metric/vmstats_sink.ex
As per 
https://docs.datadoghq.com/developers/metrics/counts/
and
https://github.com/lexmag/statix/blob/master/lib/statix.ex
Statix does not currently support sending counters as `count`
Changing wrong use of `set` to `gauge` so that we're able to show reductions, io operations etc.
- set to gaguge + comment
/
> fix: set to gauge

- .gitignore
- apps/omg_child_chain/lib/omg_child_chain/application.ex
- apps/omg_child_chain/lib/omg_child_chain/fee_server.ex
- apps/omg_db/lib/omg_db/level_db.ex
- apps/omg_db/lib/omg_db/rocks_db.ex
- apps/omg_performance/lib/omg_performance/sender_manager.ex
- apps/omg_watcher/lib/omg_watcher/application.ex
This PR triages all sobelow findings in apps. 
I am not convinced that the usage of binary_to_term in the below instances is not a security issue. In all of the cases data from the db is deserialized. Even running into a DOS condition could have very negative consequences. Deserialization bugs can often lead to RCE, I am just thinking of JAVA and PHP. Can we explore alternatives? 
http://erlang.org/pipermail/erlang-questions/2001-July/003372.html (dated)
https://hexdocs.pm/sobelow/Sobelow.Misc.BinToTerm.html#content
```
[31mMisc.BinToTerm: Unsafe `binary_to_term` - High Confidence[0m
File: apps/omg_db/lib/omg_db/leveldb/core.ex
Line: 114
Function: decode_response:111
Variable: encoded
-----------------------------------------------
[31mMisc.BinToTerm: Unsafe `binary_to_term` - High …
```
> Triage Sobelow findings

- apps/omg_eth/test/support/dev_helpers.ex
https://github.com/omisego/elixir-omg/issues/929
I think it's a timeout issue, and this allows us to send in timeout value like
```
[
faucet: "0x944a81beecac91802787fbcfb9767fcbf81db1f5",
initial_funds: 1000000000000000000,
timeout: 120_000
]
```
- Check if timeout key is present in keywords
/
> feature: allow passing in timeout in opts

- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/web/plugs/health_test.exs
- apps/omg_utils/lib/omg_utils/http_rpc/response.ex
https://github.com/omisego/elixir-omg/issues/917
Added `type: [child_chain | watcher]` to `/`  response for clarity and debugging
The `/` response type has change from
```json
{"data":{"code":"operation:not_found","description":"Operation cannot be found. Check request URL.","object":"error"},"success":false,"version":"0.2.2+a48c042"}
```
to
```json
{"data":{"code":"operation:not_found","description":"Operation cannot be found. Check request URL.","object":"error"},"success":false,"version":"0.2.2+a48c042","type":"[watcher|childchain]"}
```
Deployed it locally and manually tested it. Haven't added any tests for it, yet
> 917 response service type

- docs/tesuji_blockchain_design.md
Spotted during a review done within the documentation site process.
See commit - fixes two (for now) spots where the doc has rusted a bit
na
na
> docs: fix minor out-of-dateness of the tesuji blockchain design doc

- apps/omg_watcher/lib/omg_watcher/application.ex
- apps/xomg_tasks/lib/mix/tasks/watcher.ex
Child Chain modules still loaded under Watcher app because of mix task usage for deployment.
Trying to unload Child Chain modules under Watcher.
- Purge and delete
/
> rix: unload childchain modules from watcher

- apps/omg_status/lib/omg_status/application.ex
ensure_loaded? will reload the module again.
Pull the service from env var.
- There's no other way with using tasks
/
> fix: don't reload child chain module

- apps/omg/lib/omg/state/measure.ex
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/web/controllers/alarm_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/alarm_test.exs
https://github.com/omisego/elixir-omg/issues/936
Lets try a solution and see how it behaves in the wild, metrics are available in Datadog.
- Spawn a process that does a complete copy of OMG.State state and performs the necessary computation and dies. 
/
> fix: move measurement into separate process

- .circleci/config.yml
- apps/omg/lib/omg/state/measure.ex
- apps/omg_child_chain/test/omg_child_chain/child_chain_test.exs
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/plugs/health.ex
- apps/omg_child_chain_rpc/test/fixtures.exs
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/web/plugs/health_test.exs
- apps/omg_eth/config/config.exs
- apps/omg_eth/test/omg_eth/ethereum_client_monitor_test.exs
- config/.credo.exs
Found some alarming tickets 
/
- with the introduction of releases, db credentials changed
- client_monitor_interval_ms somehow got lost
- alarms on childchain needs to be passthrough otherwise we can't see alarms!!!
Wrote some tests!
> fix: let alarms pass when healthchecks raised alarms

- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/views/error.ex
- apps/omg_watcher_rpc/lib/web/views/error.ex
https://github.com/omisego/elixir-omg/issues/938
If an exception happens in a lower stack then controller, this propagates to renderer without information about the template.
- Render server errors
/
> fix: consistent error rendering

- apps/omg/lib/omg/block.ex
- apps/omg/lib/omg/merkle.ex
- apps/omg/test/omg/block_test.exs
- apps/omg/test/omg/merkle_test.exs
This PR adds tests for all public functions in `OMG.Block`. Functions in this module that were dealing with the `MerkleTree` library have also been extracted to a separate module, for easier testing and separation of concerns. 
I didn't remove any of the existing tests.
A few notes:
- The `to_db_value` and `from_db_value` don't do anything other than validating the type of the inputs and switching from map to struct and vice versa. I'm wondering if this kind of functions wouldn't make more sense in the `DB` sub-app.
- The `to_api_format` also feels a bit out of place to me, and since I'm just getting into the codebase, I'm not sure if it would make sense to have some formatters/serializers to put that logic into. 
- The functions in `Merkle` (moved from `Block`) have typespecs defining …
> Add tests for OMG.Block and extract Merkle-related functions

- Makefile
:clipboard: /
Adds missing quotes to the `make help` section, which was returning errors:
```sh
Dont Fear the Makefile
*DOCKER DEVELOPMENT*:
make docker-start-cluster - will start everything for you, but if there are no local images
for Watcher and Child chain tagged with latest they will get pulled from our repository.
If you want to use your own image containers for Watcher and Child Chain
use make docker-watcher && make docker-child_chain.
For rapid development that replaces containers with your code changes
one can use make docker-update-watcher or make docker-update-child_chain.
BARE METAL DEVELOPMENT:
ATTENTION ATTENTION ATTENTION
-----------------------------
This presumes you want to run geth, plasma-deployer and postgres as containers
but Watcher and Child Chain bare metal. …
```
> fix: Add missing quotes to Makefile

- .circleci/ci_deploy.sh
/
To avoid caching images by using :latest tag, use git sha of the build.
- Get SHA
- Push image tagged with short git tag
/
> fix: deploy specific tag

- apps/omg_status/lib/omg_status/metric/statix.ex
- apps/omg_status/mix.exs
- mix.lock
https://github.com/omisego/elixir-omg/issues/937
Statix we used to have does not support `events` and `service_check`
- Swap statix and lock on git SHA
Same testing applies at the moment.
> feature: migrate statix to bleacherreport branch for events support

- apps/omg_watcher/config/config.exs
Cherry-picked from v0.2:
Merge pull request #970 from omisego/hotfix_sla_margin
see #970
see #970
see #970
> fix: expand the sla_margin to 23 worth of blocks by default

- apps/omg/lib/omg/block.ex
- apps/omg/test/omg/state/persistence_test.exs
- apps/omg_db/lib/db.ex
- apps/omg_db/lib/omg_db/rocks_db.ex
- apps/omg_db/lib/omg_db/rocksdb/server.ex
- apps/omg_db/test/omg_db/db_test.exs
- apps/omg_watcher/lib/omg_watcher/api/utxo.ex
- apps/omg_watcher/lib/omg_watcher/db/txoutput.ex
- apps/omg_watcher/lib/omg_watcher/utxo_exit/core.ex
- apps/omg_watcher/test/omg_watcher/db/txoutput_test.exs
- apps/omg_watcher/test/omg_watcher/utxo_exit/core_test.exs
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/utxo/response_schemas.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/utxo/responses.yaml
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/utxo_test.exs
related to the #855 effort. Driven by results from #998 
There has been some dead code in the handling of composing data for standard exits in the Watcher.
Also it has been discovered, that when child chain blocks are larger, requests to the Watcher that ask for standard exit data tend to timeout. `Block.inclusion_proof` has received some no-brainer optimizations to remove the bottleneck.
In case of `Block.inclusion_proof`, for a block of 20K txs, the time to generate the proof dropped from the timeoutable 3.5s to 0.5s. After this optimization, the blocker is now the encoding of `raw_tx`, necessary to hash it. If necessary the further optimization would be to somehow not have to encode, but this is more involved.
- removes dead code
- tidies the flows, adds some tests conforming to the …
> Tidy composing SEs and prevent timeouting of request to the Watcher

- apps/omg_performance/lib/omg_performance/byzantine_events.ex
Workaround for #1031, but not a fix to the root cause yet.
Sleeping a while makes it pass rather reliably, but I'm leaving up to #1031 to investigate why.
Note the intention here is just to allow us to CI reliably for the time being. Proper fix is still required.
Allows the dust to settle after the watcher having been synchronized using a `Process.sleep`
```
mix test --only integration test/omg_performance/integration/byzantine_event_test.exs
```
many times
> fix: prevent flaky byzantine events test, dirty

- apps/omg/lib/omg/dev_crypto.ex
- apps/omg/lib/omg/fees.ex
- apps/omg/lib/omg/state/transaction/signed.ex
- apps/omg/test/omg/fees_test.exs
- apps/omg/test/omg/state/transaction_test.exs
- apps/omg/test/support/test_helper.ex
- apps/omg_child_chain/test/omg_child_chain/integration/happy_path_test.exs
- apps/omg_eth/lib/omg_eth/release_tasks/set_contract.ex
- apps/omg_performance/lib/omg_performance/sender_server.ex
- apps/omg_performance/test/omg_performance/integration/performance_test.exs
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/tools.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/piggyback_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/in_flight_exit_test.exs
As title:
- no need for padding with empty signatures
- explain the test of one cornercase test in FeesTest
- remove some completetly stale ones
- prevent `performance_test.exs` from timeouting - they were just under the timeout threshold. It went over the threshold when going ALD
...
usual testing, `mix test` mainly
> refactor: clean TODOs - remove stale ones and fix easy ones

- docker-compose-watcher.yml
- docker-compose.yml
Unbreak docker-compose to use the contracts + plasma-deployer from mix.lock plasma_contracts SHA.
- Plasma-deployer
- Watcher for community to use the last master build before ALD 
/
> fix: plasma deployer fix and watcher without ALD for community

- .circleci/ci_deploy.sh
- .circleci/ci_publish.sh
Aligning docker hash tag images with github 7 chars.
Creating and tagging
/
> fix: standardise image hash

- apps/omg/lib/omg/state/transaction/recovered.ex
- apps/omg/lib/omg/state/transaction/validator.ex
- apps/omg/test/omg/state/core_test.exs
- docs/transaction_validation.md
Noticed this a while ago, an opportunity to refactor, clean & simplify
Reduces the API of Transaction.Recovered, removes the confusing `can_apply?` duplication and keeps the flows simpler
Moves `Transaction.Recovered.can_apply?` to `State.Validator` and rearranges the functions a little bit.
Also, since I'm touching these lines anyway, I decided to fix the typo `unauthorized_spent`.
`mix test`
> refactor: tidy Transaction.Recovered.can_apply? a bit

- docker-compose.yml
- plasma-contract.Dockerfile
https://github.com/omisego/plasma-contracts/issues/400
Updated `plasma-deployer` and `geth`
- Updated plasma-deployer to use `truffle`, and make `geth --dev` address generation deterministic
1. `docker-compose up geth`
2. `docker-compose up plasma-deployer`
> updated plasma-deployer and geth deterministic address

- apps/omg_eth/test/omg_eth/subscription_worker_test.exs
📋 Closes #1069
Changes the port to avoid collision with other [websocketex agent mock](https://github.com/omisego/elixir-omg/blob/master/apps/omg_eth/test/omg_eth/ethereum_client_monitor_test.exs#L28).
Changes the port so they don't collide.
```
mix test --include common
```
> use different port for subscription worker

- apps/omg_child_chain_rpc/priv/swagger/operator_api_specs.yaml
- apps/omg_child_chain_rpc/priv/swagger/operator_api_specs/block/request_bodies.yaml
- apps/omg_child_chain_rpc/priv/swagger/operator_api_specs/transaction/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/informational_api_specs.yaml
- apps/omg_watcher_rpc/priv/swagger/informational_api_specs/account/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/informational_api_specs/block/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/informational_api_specs/transaction/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/account/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/in_flight_exit/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/transaction/request_bodies.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/utxo/request_bodies.yaml
:clipboard: https://github.com/omisego/specs/pull/8
This adds names to the swagger schema objects so we don't get generic titles like `InlineObject1`.
Adds a `title:` key to all the `request_bodies.yaml`
Generate the swagger:
```sh
make operator_api_specs
make informational_api_specs
make security_critical_api_specs
```
> Add titles to request body schemas for swagger

- README.md
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/release_tasks/set_endpoint.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/release_tasks/set_tracer.ex
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/release_tasks/set_tracer_test.exs
- apps/omg_db/lib/omg_db/release_tasks/set_key_value_db.ex
- apps/omg_eth/lib/omg_eth/release_tasks/set_ethereum_client.ex
- apps/omg_status/lib/omg_status/release_tasks/set_sentry.ex
- apps/omg_status/lib/omg_status/release_tasks/set_tracer.ex
- apps/omg_status/test/omg_status/release_tasks/set_tracer_test.exs
- apps/omg_watcher/config/config.exs
- apps/omg_watcher/config/dev.exs
- apps/omg_watcher/lib/omg_watcher/release_tasks/set_child_chain.ex
- apps/omg_watcher/lib/omg_watcher/release_tasks/set_db.ex
- apps/omg_watcher/lib/omg_watcher/release_tasks/set_exit_processor_sla_margin.ex
- apps/omg_watcher/lib/omg_watcher/release_tasks/set_tracer.ex
- apps/omg_watcher/test/omg_watcher/release_tasks/set_exit_processor_sla_margin_test.exs
- apps/omg_watcher/test/omg_watcher/release_tasks/set_tracer_test.exs
- apps/omg_watcher_rpc/lib/release_tasks/set_endpoint.ex
- apps/omg_watcher_rpc/lib/release_tasks/set_tracer.ex
- apps/omg_watcher_rpc/test/omg_watcher_rpc/release_tasks/set_tracer_test.exs
- rel/config.exs
fixes #1079 
A cherrypick from `v0.2` led to an invalid entry in the configuration for `:exit_processor_sla_margin`. This fixes that, introducing a new config provider, see commit `
fix: introduce a config provider for exit_processor_sla_margin setting`
On top of the actual fix, I ran into a couple of things to tidy around the release_tasks (separate commit `style: cleanup release_tasks`):
- change log level from warn to info
- add more teardown procedures in tests (in cases where it was missing)
- use catch_exit in all tests
`mix test`
> Fix sla margin config

- .circleci/config.yml
- docker-compose.yml
This PR builds Watcher and Child Chain and invokes `docker-compose up -d` and proceeds with `make get-alarms` proving that all services booted correctly, which means, you're able to run `docker-compose up` locally and develop towards it.
- Add circle CI step that supports docker-compose 2.1
The test is the test itself.
> test docker-compose and release generation

- .circleci/config.yml
- .circleci/status.sh
- Makefile
- apps/omg_watcher/test/fixtures.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs
- docker-compose.yml
This PR builds Watcher and Child Chain on baremetal and invokes `make start-services` (geth, plasma-deployer, postgres) and proceeds with `make get-alarms` proving that all services booted correctly, which means, you're able to run elixir-omg baremetal locally and develop towards it.
- run bin/setup to install dependencies
- Add circle CI step with machine executor
The test is the test itself.
>  test baremetal release  #1087 

- docker-compose.yml
Closes #1098
`{:error, %{"code" => -32000, "message" => "unknown account"}` is returned from geth when the childchain submits a block. This is due to how the docker-compose setup relies on the authority account to be unlocked but it was not configured in geth.
- Configure the authority keystore into geth
- Add `--unlock "0,1"` to unlock the two accounts
- Provide a blank password file into geth since it is needed for the `--unlock` argument
- Set `--miner.etherbase` to the deployer address so we do not depend on the accounts ordering which is prone to change
Tested with:
```
$ docker-compose up
$ npm run childchain-deposit
...
Alice's new rootchain balance: 115792089237316195423570985008687907853269984665640564039456737018433129639927
Alice's new childchain balance: 500000000000000000
$ …
```
> fix: load both deployer and authority priv keys into docker-compose's geth

- README.md
- apps/omg/config/test.exs
- apps/omg/test/test_helper.exs
- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_child_chain/test/test_helper.exs
- apps/omg_eth/config/test.exs
- apps/omg_eth/lib/omg_eth/transaction.ex
- apps/omg_eth/test/fixtures.exs
- apps/omg_eth/test/support/dev_geth.ex
- apps/omg_eth/test/support/dev_helper.ex
- apps/omg_eth/test/support/dev_node.ex
- apps/omg_performance/test/fixtures.exs
- apps/omg_performance/test/test_helper.exs
- apps/omg_watcher/test/fixtures.exs
- apps/omg_watcher/test/test_helper.exs
- docker-compose-fixtures.yml
Cherry picked from #1106 
Adds support to run integration tests (and the chch/watcher as a whole) against `ganache-cli`. Should be useful immediately (was when I was doing #1106) and as a baby step towards the new integration testing.
Contrary to `geth`/`parity` it doesn't auto-start `ganache` when doing integration tests, bring your own RPC. There's little point in providing this auto-start, facing impending revamp of integration tests.
- BlockQueue doesn't like the way `ganache` handles submitted transactions. This looks like a discrepancy wrt. other nodes. Submitted transactions here contribute to the addresses nonce, while for other nodes, only mined transactions do. This is punted now just by turning what would be an error into a warnings, logging and moving on (only if `eth_node: …
> Add ganache support for convenience/new integration tests

- rel/config.exs
If `SetContract` is run before `SetEthereumClient` then SetContract cannot make a call to retrieve   
minExitPeriod.
- Order!
/
> fix: order of config providers is important

- apps/omg/lib/omg/state/core.ex
- apps/omg/test/omg/state/core_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/happy_path_test.exs
Found when #855 
When doing ALD compatibility, I managed to introduce a bug, where `input` piggybacks would crash the child chain (a bit silently, b/c #1141, hence our integration tests didn't pick this up)
- fix bug - now child chain will completetly ignore input piggybacking events (like it did before). The bug manifests with this being thrown from the child chain server, when one piggybacks on input:
```
(omg) lib/omg/state/core.ex:387: OMG.State.Core.find_utxo_matching_piggyback(%{eth_height: 576, event_signature: "InFlightExitInputPiggybacked(address,bytes32,uint16)".........
...
** (EXIT) an exception was raised:
** (FunctionClauseError) no function clause matching in OMG.State.Core.find_utxo_matching_piggyback/2
...
```
- added an explicit `OMG.State.Core` test for this
- added a …
> fix: fix, simplify and tidy exiting from piggyback events in OMG.State

- apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/tx_appendix.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs
Found when doing #855 
Bug fix + test + some required tidies. When standard exits are confronted with IFE transactions, we forgot to recheck whether the SE is active (e.g. not challenged). This manifested only when there was a coinciding IFE spending that the exiting output.
Add the missing filtering for active exits.
`mix test` but also you can:
1. submit a tx1 and then submit another tx, spending from the first one's output
2. ife from that tx1
3. se from its tx1 output
4. challenge that se
5. observe that the se still shows up as invalid
> fix: prevent from SE challenges from being ignored, when IFE is present

- apps/omg_eth/lib/omg_eth/root_chain.ex
I was working on: https://github.com/omisego/security-issues/issues/7 when I noticed this 🗡 
https://github.com/omisego/plasma-contracts/blob/a360d5f68929f1f727104a7b4ab2e63bbc8a4327/plasma_framework/contracts/src/exits/payment/PaymentExitDataModel.sol#L21
- uint size incorrect on elixir side
/
> fix: standard exit struct specs

- apps/omg/config/config.exs
- apps/omg_child_chain/config/dev.exs
We've been pulling events every 500 ms, which is obviously too much. The pull value should be less than frequency of pushed ethereum blocks (mainnet and rinkeby) + processing time 
- Increase
- remove stale configuration
/
> feature: decrese polling

- docs/standard_vs_in_flight_exits_interaction.md
:clipboard: https://github.com/omisego/plasma-contracts/issues/470
There was a bug found for cross-competin IFE with one end up canonical and one not. As a result, the logic of flagging output is changed while fixing that.
Also, trying to update for this comment: https://github.com/omisego/elixir-omg/pull/1118#issuecomment-557132890
> docs: update flagging logic for IFE

- .circleci/config.yml
Relates to #1123 
Fixes failing CircleCI's docker image publishing due to misconfigured values for watcher_info.
- Fix typo `watcher_info_IMAGE_NAME:` from the app rename
- `publish_watcher_info` build step changed to use the `metal_watcher_info` executor so that it has the value for `$WATCHER_INFO_IMAGE_NAME`
`make publish_watcher_info` runs successfully
> fix: circleci's using wrong values to publish watcher_info

- .circleci/config.yml
- bin/setup
Fixes brew installing a newer version of solidity (`0.5.13`) than the contracts' (`0.5.11`) by pinning the solidity version installed by brew.
```
Error: Source file requires different compiler version (current compiler is 0.5.13+commit.5b0b510c.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.5.11;
^---------------------^
```
ref: https://circleci.com/gh/omisego/elixir-omg/29602
- Pin Mac OS's brew to https://raw.githubusercontent.com/ethereum/homebrew-ethereum/7fa7027f20cca27f76c679d0c5b35ee3c565f284/solidity.rb which is solidity 0.5.11
Since this occurs on nightly, https://github.com/omisego/elixir-omg/commit/ba05bec3bfabc2af51304da9f75c6ca9ab90fa0e temporarily adds it to build-deploy workflow for testing and …
> fix: pin mac brew install to solidity 0.5.11

- apps/xomg_tasks/lib/mix/tasks/child_chain.ex
- apps/xomg_tasks/lib/mix/tasks/watcher.ex
- apps/xomg_tasks/lib/mix/tasks/watcher_info.ex
- apps/xomg_tasks/lib/utils.ex
Adds `mix xomg.watcher_info.start` in addition to the existing `mix xomg.watcher.start` and `mix xomg.child_chain.start`. I forgot about this in the main code split PR.
- Removed convenience api option from watcher.start and replace with a new task for watcher_info so it has closer UX to API and releases.
Run `mix xomg.watcher_info.start`. Couldn't think of a way to automate test without significant overhead. And this is a dev tool so 🤷‍♂
> feat: add `mix xomg.watcher_info.start`

- docs/tesuji_blockchain_design.md
Fixes #1208 
Reference the up-to-date and canonical docs on Transactions. Move around portions of the obsolete sections to their new sections to keep all the information present
:eyes:, follow the links and see if all is more or less coherent
> docs: remove contents of Transaction section in docs in favor of a link

- apps/omg_child_chain_rpc/config/test.exs
- apps/omg_db/lib/db.ex
- apps/omg_db/lib/omg_db/rocks_db.ex
- apps/omg_performance/lib/performance.ex
- apps/omg_watcher/config/test.exs
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs
- apps/omg_watcher_info/config/test.exs
Fixes #1180 
The problem lied in incorrect handling of a spending_block `:not_found` - `{:ok, :not_found}` was expected, but this form was since long deprecated in favor of the former.
Also this was uncleanly realized too late, so a peek into `OMG.State` was added to figure out the challengeability of the requested exit.
- fix the bug, sprinkle some tests
- change the **`test`** env `ChildChainRPC` port number to `9657` to avoid the super-annoying clash with the default
- groom the specs in `OMG.DB`
`mix test`
> fix unspent utxo challenging attempt crashing ExitProcessor

- apps/omg/lib/omg/output.ex
- apps/omg/lib/omg/state/core.ex
- apps/omg/lib/omg/state/transaction/validator.ex
- apps/omg/lib/omg/utxo.ex
- apps/omg/lib/omg/utxo/position.ex
- apps/omg/test/omg/output_test.exs
- apps/omg/test/omg/utxo_test.exs
- apps/omg_watcher/lib/omg_watcher/api/utxo.ex
- mix.lock
:clipboard: #1218 the first refactor series
This refactors `OMG.Output` to de-tangle some of its coupling with the rest of the code. This is a small refactor to pave wave for a larger refactor of the `OMG.Utxo`, `OMG.Utxo.Position`, and `OMG.OUtput` tree.
* Move guards into modules that use them. The guards that exist often are only used once. We should move them to where they are used.
* Leverage ExPlasma to do the RLP data -> struct conversion.
* Break out the error tuple generation into it's own method. Eventually we'll port this to `ex_plasma` to handle returning error messages around decoding.
* Remove `dispatching_reconstruct`. We only have 1 output to generate. For the future output models, we should be building these encoding structures into `ex_plasma`.
* Add test files for …
> Refactor OMG.Output guards and usage

- apps/omg_watcher/lib/omg_watcher/api/account.ex
- apps/omg_watcher/test/omg_watcher/api/account_test.exs
- apps/omg_watcher_rpc/lib/web/controllers/account.ex
This PR moves `OMG.WatcherInfo.API.Account.get_exitable_utxos/1` to `OMG.Watcher`. 
Thanks to @jrhite for spotting this boundary breach:
> @jrhite: Just ran across this code in WatcherInfo. Seems strange that it's in Info using OMG.DB. Curious why it's in Info, what's the rationale for it? There's a simple query for the same info in db/transaction.ex, but currently it only filters unspent or unexited txoutputs. It could be extended to also filter out txoutputs in an IFE state or other various scenarios.
> 
> Thanks!
> 
> ```
>   @doc """
>   Gets all utxos belonging to the given address.
>   Slow operation, compatible with security-critical.
>   """
>   # TODO this seems weird and a breach of decoupling
>   @spec get_exitable_utxos(OMG.Crypto.address_t()) :: …
```
> refactor: move Account.get_exitable_utxos/1 into watcher security

- apps/omg_child_chain/lib/omg_child_chain/block_queue.ex
- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_child_chain/test/omg_child_chain/block_queue/core_test.exs
BlockQueue.Core (especially tests) aged a bit, which I spotted when solving #1136. This should give those a significant refactor.
As far as I can tell, this shouldn't change `BlockQueue`'s behavior in any way.
This is a set of interleaving implementation and test changes. It might be **most convenient** to review commit-by-commit or in small batches
- **removing some dead code**
- refactor: remove BlockQueue.Core.new/0 which wasn't really used
- refactor: get rid of child_start_parent_height handling
- **mechanical and simple tidies to `CoreTests`**
- test: remove duplicate test and tighten the one that remained after
- style: rearrange existing BlockQueue.CoreTests into function `describe` blocks
- refactor: ditch the recover/3 helper in test
- **larger refactor cleaning `Core.new/1` …
> Clean block queue code

- .circleci/config.yml
- .gitignore
- Dockerfile.child_chain
- Dockerfile.watcher
- Dockerfile.watcher_info
- Makefile
- README.md
- docker-compose.dev.yml
- mix.exs
https://github.com/omisego/elixir-omg/issues/1248
This PR would identify a container build and use _build_docker and _deps_docker folders for compilation and dependencies.
- builder and tester images now have an environment variables set called `DOCKER=true` https://github.com/omisego-images/docker-elixir-omg/pull/26
- if the ENV var is populated ^^, append `_docker` string in the directory name
/
> refactor: build dir in docker

- apps/omg_eth/lib/omg_eth/ethereum_client_monitor.ex
- apps/omg_eth/lib/omg_eth/ethereum_height.ex
https://github.com/omisego/devops/issues/308
A quick suggestion following the discussion in the issue.
Add a higher level (`info`) log of `newHeads` every 1000 ethereum blocks.
Rudimentary because possibly #1255 happens, but needed to better debug problems with stalled watchers
as above + I rephrased the logs a bit - the `__MODULE__` is logged anyway per logger format, so I think we can drop it from the `Logger` invocation itself.
existing tests + we'll see the logs in dd
> feat: info-level log every 1000 newHeads received

- apps/omg_watcher_info/mix.exs
Fixes mix commands not working within `omg_watcher_info` subapp by adding `:jason` and `:omg` to `omg_watcher_info` subapp deps.
@okalouti reported problems running ecto migration generation within the `omg_watcher_info` subapp. And this command needs to be run from the subapp.
```
$ mix ecto.gen.migration index_block_timestamp
==> omg_status
Compiling 1 file (.ex)
warning: found Jason in your application configuration
for Phoenix JSON encoding, but failed to load the library.
(module Jason is not available).
Ensure Jason exists in your deps in mix.exs,
and you have configured Phoenix to use it for JSON encoding by
verifying the following exists in your config/config.exs:
config :phoenix, :json_library, Jason
(phoenix) lib/phoenix.ex:40: Phoenix.start/2
(kernel) …
```
> fix: add :jason and :omg as omg_watcher_info dependencies

- apps/omg_eth/lib/omg_eth/release_tasks/set_contract.ex
Add support for the Görli Testnet
Currently elixir-omg supports Ropsten and Rinkeby testnets. This PR adds support for the Görli testnet (https://goerli.net/). This is a simple change that allows the `ETHEREUM_NETWORK` env var to have `GOERLI` as a value.
Childchain and Watcher should be able to start with `ETHEREUM_NETWORK` set to `GOERLI`. The smart contracts are already deployed on the testnet.
> Add support for Görli testnet

- .circleci/config.yml
- docker-compose.yml
Clean up some unused and/or redundant CircleCI configs.
- Renamed `coveralls_merge` to `coveralls_report` because it's mainly doing reporting
- Removed executor `metal_child_chain`, `metal_watcher`, `metal_watcher_info`. They were stripped out and now left with only assigning a single env var each. Easier to move to the env var assignment to the actual job
- Removed `build_and_deploy_staging` job that was configured specifically for the ancient `v0.1` branch
- Grouped trivial states printing together so it's easier to browse in CircleCI
- Version-pinning hex and rebar installations
CircleCI build still passes.
> refactor: clean up circleci config

- apps/omg_child_chain/lib/omg_child_chain/fees/single_spec_parser.ex
- apps/omg_child_chain/priv/fee_specs.json
- apps/omg_child_chain/test/omg_child_chain/fees/single_spec_parser_test.exs
This PR adds logic on the fee parser to allow pegged fields to be nil.
For one currency, either all pegged fields or none should be nil.
> Allow all pegged fee fields to be nil

- Makefile
- apps/omg/lib/omg/state/transaction/payment.ex
- config/.credo.exs
- config/credo/license_header.ex
- config/credo/require_parentheses_on_zero_arity_defs.ex
- mix.exs
Forces credo to exit with bad status when it found custom lint errors. Also piggybacking geth snapshot cleanups.
- Moved custom linting into `Credo.Check.Warning` and `Credo.Check.Readability` namespace so it derives the exit status from https://github.com/rrrene/credo/blob/master/lib/credo/check.ex#L48-L54
- Moved geth snapshot to `make init-contracts` since now it's used a lot to setup docker-compose for multiple use cases.
- Alias `make init_test` to `make init-contracts`
- `make docker-nuke` and `make clean` also cleans up geth data folder, since the geth data will no longer be compatible with new containers
Linting should exit with error like this: https://app.circleci.com/jobs/github/omisego/elixir-omg/40258/parallel-runs/0/steps/0-103
> feat: credo should complain of custom lintings and better make clean/nuke commands

- apps/omg_watcher/test/omg_watcher/integration/block_getter_test.exs
Closes omisego/feat-fee/issues/29
Resolves omisego/feat-fee/issues/21
After #1244 - operator claim fees with each block. Watcher needs to protect against claim frauds.
Because [fee txs are __executed__ on state](https://github.com/omisego/feat-fee/issues/28#issuecomment-567440923) Watcher should already be warned by incorrect state when too much / not collected fees are claimed. We just need a test to demonstrate this.
Added `test operator claim more fees than collected (OMG.Watcher.Integration.BlockGetterTest)`
> Watcher discovers fraudulent claim and publishes byzantine event

- apps/omg_watcher/test/support/watcher_helper.ex
- apps/omg_watcher_info/lib/omg_watcher_info/http_rpc/adapter.ex
- apps/omg_watcher_info/test/omg_watcher_info/http_rpc/adapter_test.exs
- apps/omg_watcher_rpc/lib/web/controllers/fallback.ex
- apps/omg_watcher_rpc/lib/web/controllers/fee.ex
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/fee_test.exs
Closes #1308 
This PR adds the support for Poison connection error when the watcher queries the childchain in `fees.all`. 
Run a watcher with a childchain that is unreachable and call `fees.all`
> Fix: handle error when childchain is unreachable

- .formatter.exs
Previous PR: https://github.com/omisego/elixir-omg/pull/1323 forgot to use `wildcard` when using `*` on path, causing format failure once you have swagger client generated.
- use `Path.wildcard`
`mix format --check-formatted` with swagger client generated
> fix: formatter using * without wildcard

- apps/omg_child_chain_rpc/config/config.exs
- apps/omg_status/mix.exs
- apps/omg_watcher_rpc/config/config.exs
- mix.lock
We've seen occurrences of
```
error] module=Plug.Cowboy function=onresponse/4 ⋅Cowboy returned 400 because it was unable to parse the request headers.
--
  | Feb 20 04:00:17.860 | This may happen because there are no headers, or there are too many headers
  | Feb 20 04:00:17.860 | or the header name or value are too large (such as a large cookie).
  | Feb 20 04:00:17.860 | You can customize those values when configuring your http/https
  | Feb 20 04:00:17.860 | server. The configuration option and default values are shown below:
  | Feb 20 04:00:17.860 | protocol_options: [
  | Feb 20 04:00:17.860 | max_header_name_length: 64,
  | Feb 20 04:00:17.861 | max_header_value_length: 4096,
  | Feb 20 04:00:17.861 | max_headers: 100,
  | Feb 20 04:00:17.861 | max_request_line_length: 8096
  | Feb …
```
> double the max_header_value_length

- apps/omg_watcher_rpc/lib/web/plugs/supported_watcher_modes.ex
- apps/omg_watcher_rpc/lib/web/router.ex
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/router_test.exs
Closes #1292 
This PR fixes the internal server error returned when requests are made to the unsupported watcher mode.
- `Plugs.SupportedWatcherModes` halts the pipeline on error so no further processing is done
- `plug(:accepts, ["json"])` is moved above `Plugs.SupportedWatcherModes` so Phoenix knows to render the error template as json.
An informational API call to watcher should render proper error:
```
curl -X POST http://watcher-not-watcher-info/transaction.all \
-H "Content-Type: application/json" \
-d '{}' \
-v -w "\n" | jq
{
"data": {
"code": "operation:not_found",
"description": "Operation cannot be found. Check request URL.",
"object": "error"
},
"service_name": "watcher",
"success": false,
"version": "0.3.0+dc971b2"
}
```
> fix: internal server error when making requests to unsupported endpoints

- apps/omg/lib/omg/ethereum_event_listener.ex
- apps/omg_child_chain/lib/omg_child_chain/datadog_event/contract_event_consumer.ex
- apps/omg_child_chain/test/omg_child_chain/datadog_event/contract_event_consumer_test.exs
- apps/omg_watcher/lib/omg_watcher/block_getter.ex
- apps/omg_watcher/lib/omg_watcher/datadog_event/contract_event_consumer.ex
- apps/omg_watcher/test/omg_watcher/datadog_event/contract_event_consumer_test.exs
- bin/variables
When Watchers detect a block submitted event from Ethereum, publish it on omg bus so that consumers can do whatever they want with it.
- find where it's detected and publish it
> publish BlockSubmitted event

- .circleci/config.yml
Fix CircleCI not running CI on git tags
By default, tags do not trigger CI jobs and the only way to enable it is through `only:` config. And so because we add `only:` config we need to add one for branches too.
Sources:
- https://discuss.circleci.com/t/builds-for-tags-not-triggering/17681
- https://discuss.circleci.com/t/build-workflow-not-triggered-when-tag-is-pushed/19577
Merge this PR. Push a new tag. CircleCI should run on tags now.
> fix: run CircleCI builds on tags

- .circleci/config.yml
Relates to #1366 
Another attempt to make CircleCI build docker images for version tags.
The previous PR #1366 made some progress by having the [`build` job executed on tags](https://app.circleci.com/github/omisego/elixir-omg/pipelines/376f16be-e2c4-4d09-bfd2-846a19286c0d/workflows/3145a22b-835b-4bc8-9a92-00d1f9e2be84). Now we need to bring up the rest of the workflow.
Enable the rest of build, test and publish jobs enabled on tags. This aligns with the [ewallet's CircleCI](https://github.com/omisego/ewallet/blob/master/.circleci/config.yml#L235-L255) where docker images are being published on tags correctly.
Merge this PR and tag a new release.
> fix: add tags filter to CircleCI workflow jobs

- docs-ui/0.4/info_api_specs.yaml
- docs-ui/master/info_api_specs.yaml
Relates to #1362
Mirrors the API specs fix from master branch's https://github.com/omisego/elixir-omg/pull/1362/commits/743d1bc63260b1f36224703b2dbed0419d0fefef
> docs: fix wrong indentation in API specs

- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/finalizations.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/piggyback.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/finalizations_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/piggyback_test.exs
- apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs
- apps/omg_watcher/test/support/exit_processor/test_helper.ex
Closes #1371 
It is the "Quick fix" mentioned in #1371. The larger fix #1318 would do proper justice to the handling of piggyback state (description of that in #1318 still pending), which should not be modeled with a bunch of booleans. There should also be a revamp done to the overall "lifecycle" of the piggyback, to include invalidly processing ones.
- adds a simple test picking up the case in question, in `piggyback_test.exs`
- refactors some other tests and inner working of `InFlightExitInfo`. We're interrested in the notions of 1/ "activity" of a piggyback, where it means it may finalize and we perhaps want to check if it is valid and 2/ "being piggybacked", where it means just this.
- it finally adds an explicit notion of `is_challenged` to the IFE's piggyback model. Whenever a …
> Fix "piggyback_available" popping back after challenge

- .circleci/config.yml
Add a circleci config to `gh-pages` branch so it shows a proper message.
**No good:**
**Too scary:**
**Awyeah:**
The last screenshot is the one to be shown by this PR.
> feat: properly skip CircleCI on gh-pages

- priv/perf/README.md
- priv/perf/apps/load_test/.formatter.exs
- priv/perf/apps/load_test/lib/application.ex
- priv/perf/apps/load_test/lib/connection/child_chain.ex
- priv/perf/apps/load_test/lib/connection/utils.ex
- priv/perf/apps/load_test/lib/connection/watcher_info.ex
- priv/perf/apps/load_test/lib/connection/watcher_security.ex
- priv/perf/apps/load_test/mix.exs
- priv/perf/config/config.exs
- priv/perf/config/stress.exs
- priv/perf/config/test.exs
Override more on Tesla middleware for stable client.
- use Jason instead of Poison
- change the header to "perf" on Tesla here.
- add retry and retry logic to the Tesla client to keep the test alive against transient error. It is by default using exponential backoff logic ✨
- setup connection pool (`:perf_pool`) in `Application.start/2` and use the pool in Tesla client
- update README
- Jason vs Poison: https://github.com/phoenixframework/phoenix/issues/2693#issuecomment-388881650
- Tesla Middleware: https://hexdocs.pm/tesla/Tesla.Middleware.Retry.html#content
- Hackney connection pool: https://github.com/benoitc/hackney#use-the-default-pool
- Setting up `opts` for hackney: …
> chore: add more Tesla middleware overriding for a more stable client on load tests

- .circleci/config.yml
- Makefile
- apps/omg_watcher/test/omg_watcher/integration/block_getter_test.exs
- apps/omg_watcher/test/omg_watcher/integration/invalid_exit_test.exs
- apps/omg_watcher/test/support/integration/test_helper.ex
- bin/variables_test_barebone
- priv/cabbage/Makefile
- priv/cabbage/apps/itest/lib/account.ex
- priv/cabbage/apps/itest/lib/api_model/challenge_data.ex
- priv/cabbage/apps/itest/lib/plasma_framework.ex
- priv/cabbage/apps/itest/lib/poller.ex
- priv/cabbage/apps/itest/lib/standard_exit_challenge_client.ex
- priv/cabbage/apps/itest/lib/standard_exit_client.ex
- priv/cabbage/apps/itest/test/features/in_flight_exits.feature
- priv/cabbage/apps/itest/test/features/invalid_standard_exits.feature
- priv/cabbage/apps/itest/test/features/standard_exits.feature
- priv/cabbage/apps/itest/test/itest/configuration_api_test.exs
- priv/cabbage/apps/itest/test/itest/deposits_test.exs
- priv/cabbage/apps/itest/test/itest/fee_claiming_test.exs
- priv/cabbage/apps/itest/test/itest/in_flight_exits_test.exs
- priv/cabbage/apps/itest/test/itest/invalid_standard_exit_test.exs
- priv/cabbage/apps/itest/test/itest/standard_exit_test.exs
- priv/cabbage/apps/itest/test/test_helper.exs
- priv/cabbage/config/config.exs
- priv/cabbage/docker-compose-cabbage.yml
Fixes #1333 
This is a still quite tentative take on how to turn invalid (standard) exit tests into cabbage tests.
I'm having many doubts about the approach and I'll probably experiment with alternative approaches (see below).
I'm keeping the tidied up "old" approach tests, as I'd like to first gain more confidence in the cabbage tests added.
- does some necessary intro fixes to the "old" integration tests which were not strict enough
- separates those tests into two "kinds"
- tests requiring an invalid block (not moving to cabbage yet)
- tests not requiring an invalid block (this is moving)
- turns ~one~ three of those tests into cabbage tests
- tried to stick by conventions, but did some refactors: added `Itest.PlasmaFramework` to group related tools dispersed across modules, made …
> Cabbagize invalid exit tests

- apps/omg_watcher_rpc/priv/swagger/info_api_specs.yaml
- apps/omg_watcher_rpc/priv/swagger/info_api_specs/account/response_schemas.yaml
- apps/omg_watcher_rpc/priv/swagger/info_api_specs/account/schemas.yaml
- apps/omg_watcher_rpc/priv/swagger/info_api_specs/transaction/response_schemas.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/account/response_schemas.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs/account/schemas.yaml
**info_api_specs**
AccountAPI
- AccountUtxoSchema: added missing swagger fields for creating_txhash, spending_txhash, otype
- AccountUtxoResponseSchema: updated examples
TransactionAPI
- Update examples
**security_api_specs**
- AccountUtxoSchema remove time fields and update example
> fix: add missing fields to swagger

- .circleci/config.yml
References: https://github.com/omisego/elixir-omg/issues/1428
As currently tests of load tests do not measure performance drops and are just smoke tests of load test scenarios functionality I removed running them from CI job.
Removes running smoke load tests on `build_test_deploy` CI job.
> test: do not run load tests on deployed dev env

- apps/omg_child_chain/lib/omg_child_chain/block_queue/gas_analyzer.ex
- apps/omg_child_chain/test/omg_child_chain/block_queue/gas_analyzer_test.exs
https://github.com/omisego/elixir-omg/issues/1427
A bug was discovered when tx hash gets rejected from the pool, we would try to get gas indefinitely. 
Adds an index to tx hash that gets queued in Gas Analyzer, and removes the tx hash after 3 retries.
```
mix test test/omg_child_chain/block_queue/gas_analyzer_test.exs
```
> retry index and dequeue

- .circleci/config.yml
- apps/omg_performance/lib/omg_performance/generators.ex
- apps/omg_performance/test/omg_performance/byzantine_event_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs
- bin/setup
Fixing nightly builds and moving them to main build but they're not mandatory for merge.
This way they're easier to observe when they get broken by PRs.
Mac build and barebone build fixes
- Input and ouput sort as per DB query
- Install Solidity 5.11 via RB url 
Tests were already failing. Hopefully they'll pass now.
> fix: solidity install

- .circleci/config.yml
Fixes CI lint_version [failing](https://app.circleci.com/pipelines/github/omisego/elixir-omg/6262/workflows/2d905f0d-e037-4a95-a1ae-d21331d4ec3b) when tagged with pre-release versions e.g. `v0.4.7-pre.0`.
- Update `lint_version` CI job to exclude the pre-release section of the tag before comparing with `VERSION` file.
- Tested against bash shell
```sh
$ CIRCLE_TAG=v0.4.7
$ echo "${${CIRCLE_TAG#*v}%%-pre.*}"
0.4.7
$ CIRCLE_TAG=v0.4.7-pre.0
$ echo "${${CIRCLE_TAG#*v}%%-pre.*}"
0.4.7
$ CIRCLE_TAG=v0.4.7-pre.99
$ echo "${${CIRCLE_TAG#*v}%%-pre.*}"
0.4.7
```
- Future CI jobs on pre-release tags should pass `lint_version`
> fix: lint_version CI job to let pre-release versions match VERSION

- priv/perf/apps/load_test/lib/child_chain/deposit.ex
- priv/perf/apps/load_test/lib/child_chain/utxos.ex
- priv/perf/apps/load_test/lib/service/faucet.ex
Modify the load test faucet to only do a deposit if necessary. This can greatly speed up testing by pre loading the faucet account.
- Stop the faucet from always doing a deposit on init()
- When asked to fund an account, the faucet checks if it has sufficient funds, and deposits more if not 
Closes https://github.com/omisego/omg-load-testing/issues/44
> Modify the load test faucet to only deposit when necessary

- apps/omg_child_chain/test/omg_child_chain/release_tasks/set_fee_claimer_address_test.exs
Fixes #1447 
Add missing test of release task of setting fee claimer address
```
OMG.ChildChain.ReleaseTasks.SetFeeClaimerAddressTest
* test address has to have a proper length of 20-bytes (5.9ms)
* test address has to be HEX encoded string (2.3ms)
* test when configured properly correct address is set (0.03ms)
* test zero address is not accepted value (0.04ms)
* test env var has always to be set or task will fail (0.02ms)
* test chars casing or leading 0x do not affect the value (0.03ms)
```
> Add missing test of release task of setting fee claimer address

- apps/omg_child_chain/lib/omg_child_chain/block_queue.ex
- apps/omg_child_chain/lib/omg_child_chain/block_queue/balance.ex
- apps/omg_child_chain/lib/omg_child_chain/block_queue/measure.ex
- apps/omg_child_chain/lib/omg_child_chain/sync_supervisor.ex
- apps/omg_child_chain/test/omg_child_chain/block_queue/balance_test.exs
- apps/omg_child_chain/test/omg_child_chain/ethereum_event_aggregator_test.exs
- apps/omg_status/lib/omg_status/alert/alarm_printer.ex
- apps/omg_status/lib/omg_status/metric/event.ex
- apps/omg_status/lib/omg_status/release_tasks/set_tracer.ex
- apps/omg_status/test/omg_status/alert/alarm_printer_test.exs
- apps/omg_watcher/lib/omg_watcher/block_getter/supervisor.ex
- apps/omg_watcher_info/lib/omg_watcher_info/deposit_consumer.ex
- priv/cabbage/apps/itest/lib/contract_event.ex
This PR removes one of the custom bots from devops
On block submission, this process checks the balance of the authority address, logs and send a telemetry event.
- add a process with async balance check
- test that simple process
mix test
> observe the authority address balance on block submission

- apps/omg_child_chain/lib/omg_child_chain/datadog_event/contract_event_consumer.ex
- apps/omg_child_chain/test/omg_child_chain/datadog_event/contract_event_consumer_test.exs
- apps/omg_watcher/lib/omg_watcher/datadog_event/contract_event_consumer.ex
- apps/omg_watcher/test/omg_watcher/datadog_event/contract_event_consumer_test.exs
Fixes a bug in setting contract event consumer id and topic.
> fix: require origin for contract event consumer topic

- apps/omg_eth/lib/omg_eth/application.ex
- apps/omg_eth/test/omg_eth/application_test.exs
We used to call this `authority_addr` but it was changed in the elixir bump PR. but since hash is being calculated from the whole map, keys need to match as well.
https://github.com/omisego/elixir-omg/commit/e8d71a946061982b3087b7e8637f1fcb1490e78e#diff-e41e0520c4a94ce982c5ce2346cd7d27L55
> keep authority_addr naming for phash2 for backwards compatibility

- docs/install.md
I've recently run setup on clean Ubuntu machine just to find our instruction are broken.
> Update installation instructions

- README.md
Recent domain changes require an update of all APIs references. All Swagger docs have moved from `developer.omisego.co` to `docs.omg.network` domain.
- Replaced outdated domain with `docs.omg.network` for all API specifications.
> fix: API links

- .circleci/config.yml
- priv/cabbage/Makefile
https://github.com/omisego/elixir-omg/pull/1450#issuecomment-611920723
Fix the issue where a logging command is invoked after `make start_daemon_services` failure, which causes the return status to be of the logging command and so CircleCI thinks the step passes.
Updated circleci config to capture the start services result and return it after logging.
Tested on CircleCI: https://app.circleci.com/pipelines/github/omisego/elixir-omg/6449/workflows/67b5c631-d037-43e8-b863-473c34a08e47/jobs/54984 Error shown as expected:
```
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-cabbage.ym'
Makefile:12: recipe for target 'start_daemon_services' failed
make: *** [start_daemon_services] Error 1
Attaching to 
Exited with code exit status 2
CircleCI received exit code 2 …
```
> fix: circleci to return the original start-services result after logging the failure

- apps/omg_child_chain/lib/child_chain.ex
- apps/omg_child_chain/lib/omg_child_chain/api/alarm.ex
- apps/omg_child_chain/lib/omg_child_chain/api/configuration.ex
- apps/omg_child_chain/lib/omg_child_chain/api/transaction.ex
- apps/omg_child_chain/lib/omg_child_chain/application.ex
- apps/omg_child_chain/lib/omg_child_chain/measure.ex
- apps/omg_child_chain/test/omg_child_chain/api/transaction_test.exs
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/transaction.ex
- apps/omg_status/lib/omg_status/metric/event.ex
- apps/omg_watcher/lib/omg_watcher/api/transaction.ex
Add metrics for child chain's transaction submissions received, successfully processed and failed to process.
- Add `OMG.ChildChain.API.Transaction` in between `OMG.ChildChainRPC.Web.Controller.Transaction` and `OMG.ChildChain` to emit telemetry events
- Add `OMG.ChildChain.Measure` to start receiving the telemetry events and report it to the metrics collector (Statix/Datadog)
```shell
mix test test/omg_child_chain/api/transaction_test.exs
```
Once deployed, each `/transaction.submit` to the child chain should affect the following metrics:
- **Successful submission:**
- `transaction_submission` metric increases by 1
- `transaction_submission_success` metric increases by 1
- **Failed submission:**
- `transaction_submission` metric increases by 1
- `transaction_submission_failed` metric …
> feat: add child chain metrics for transaction submissions, successes and failures

- .circleci/config.yml
- Makefile
- docker-compose.yml
Previously when running docker-compose, the rocksdb data dir was stored inside the `childchain`, `watcher` and `watcher_info` docker containers, which meant that they were lost every time the container was restarted, so the services were out of sync with local geth, which meant that any time you had to start a new chain and redeploy the contracts again on every restart.
Moving the rocksdb data dir out of the container makes it persistent, so that the services can be restarted and they will pick up where they left off. 
- In docker-compose.yaml, mount `/data` as a volume and use it as the rocksdb data dir for `childchain`, `watcher` and `watcher_info`. Same pattern as the `geth` container.
> Move db storage out of docker containers

- apps/omg_status/lib/omg_status/monitor/memory_monitor.ex
- apps/omg_status/test/omg_status/monitor/memory_monitor_test.exs
Closes #1484
This PR skips buffered and cached memory in memory usage calculation if the running OS does not provide them.
- Consider buffered and cached memory as 0 if not provided.
```
mix test test/omg_status/monitor/memory_monitor_test.exs
```
Running elixir-omg on MacOS should no longer crash the monitor
> fix: MemoryMonitor breaking on OS that does not provide buffered and cached memory data

- apps/omg_status/lib/omg_status/release_tasks/set_sentry.ex
- apps/omg_status/test/omg_status/release_tasks/set_sentry_test.exs
Closes #1478
Fix sentry throwing an error due to unexpected tags data type.
See https://github.com/getsentry/sentry-elixir#configuration, tags need to be passed as maps.
- Convert sentry tags from keywords to maps
`mix test test/omg_status/release_tasks/set_sentry_test.exs` should pass and exceptions being sent to Sentry.
> fix: configure sentry tags as maps

- .circleci/config.yml
- apps/omg/lib/omg/root_chain_coordinator.ex
- apps/omg/lib/omg/root_chain_coordinator/core.ex
- apps/omg/test/omg/root_chain_coordinator/core_test.exs
If you want to receive exit signals from processes you need to monitor them. I don't see any code implying that RootChainCoordinator monitors Ethereum Event Listeners and these two chunks of code would ever get called. So I'm removing them.
> who monitors the monitor

- .circleci/config.yml
Blocks #1499
Bash doesn't support nested parameter expansion [[1]](https://stackoverflow.com/questions/917260/can-var-parameter-expansion-expressions-be-nested-in-bash) [[2]](https://stackoverflow.com/questions/6724056/can-parameter-expansion-be-nested-in-bash) [[3]](https://unix.stackexchange.com/questions/186942/multiple-variable-expansion-modifiers-in-the-same-expression), which currently breaks #1499. This PR breaks them into multiline.
This error was originally raised in v0.4 branch so targeting this PR to v0.4. It'll be merged into master as part of #1499.
Updated lint_version circleci job to break down the version step by step.
CircleCI tagged builds should pass.
> fix: lint_version compatibility with bash

- apps/omg/test/support/test_helper.ex
- apps/omg_child_chain/lib/omg_child_chain/fees/json_fee_parser.ex
- apps/omg_child_chain/lib/omg_child_chain/fees/json_single_spec_parser.ex
- apps/omg_child_chain/test/omg_child_chain/fees/feed_adapter_test.exs
- apps/omg_child_chain/test/omg_child_chain/fees/file_adapter_test.exs
- apps/omg_child_chain/test/omg_child_chain/fees/json_fee_parser_test.exs
- apps/omg_child_chain/test/omg_child_chain/fees/json_single_spec_parser_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/fee_server_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/fixtures.exs
- apps/omg_child_chain/test/omg_child_chain/support/fee_specs.json
- bin/variables_test_barebone
- priv/dev-artifacts/fee_specs.dev.json
I was preparing demo to show Child-chain & Fee Service integration. I discovered that ch-ch can parse slightly different fee rules format that FeeService publishes.
I made just the needed changes to make ch-ch understand rules from feed.
I made tests green.
Also fee rules from FeeService does not fully complies to what was [agreed before](https://github.com/omisego/feat-fee/issues/18), :writing_hand: ~~so I've created an [issue](https://github.com/omisego/feefeed/issues/20)~~ Fee feed response has been adapted in [this PR](https://github.com/omisego/feefeed/pull/21)
- [fee rules format](https://github.com/omisego/feat-fee/issues/18)
- [Fee service's issue](https://github.com/omisego/feefeed/issues/20)
I just made the needed …
> Making Child-chain work with fee feed

- apps/omg_child_chain/lib/omg_child_chain/block_queue/gas_price_adjustment.ex
Relates to #1523
Increase the hardcoded max gas price to 85 gwei. Ideally should make it configurable but this should work for the time being.
- Increase max_gas_price to 85_000_000
Block submission should be successful in timely manner.
> feat: update max_gas_price to 85_000_000

- apps/omg_watcher_rpc/lib/web/controllers/fallback.ex
- apps/omg_watcher_rpc/lib/web/controllers/transaction.ex
- apps/omg_watcher_rpc/lib/web/validators/order.ex
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs
Since the introduction of fees (and the overpaying error), merges cannot be created properly via `/transaction.create`. Since merges are free, but the `/transaction.create` generates transactions with fees included, it's currently returning paid merges which are rejected by the childchain.
`/transation.create` is currently returning invalid txs to the users.
To counter that, we thought about a few options, like trying to detect merges and not setting fees for them. Unfortunately, due to the way this endpoint works (only specifying outputs and selecting UTXOs for inputs), it's really hard to deduce if the user wants to do a merge or a split. 
Therefore, we've decided to prevent the creation of merges and splits via `/transaction.create` entirely, simply by checking that the `owner` address …
> Prevent split/merge creation in /transaction.create

- apps/omg_watcher_info/lib/omg_watcher_info/db/eth_event.ex
- apps/omg_watcher_info/lib/omg_watcher_info/db/txoutput.ex
- apps/omg_watcher_info/lib/omg_watcher_info/exit_consumer.ex
- apps/omg_watcher_info/lib/omg_watcher_info/supervisor.ex
- apps/omg_watcher_info/test/omg_watcher_info/db/eth_event_test.exs
- apps/omg_watcher_info/test/omg_watcher_info/exit_consumer_test.exs
Addresses #1520 needed for 0.4.9 😑 
Reporting appropriate event type from Watcher-Info's exit consumer.
Pushing appropriate event type to the `ExitConsumer` so the correct type of the spending event can be persisted in Postgres DB.
Exit consumer tests cover the change.
> feat: add event type when consumer is spending utxos

- apps/omg/lib/omg/root_chain_coordinator.ex
- apps/omg_watcher/lib/omg_watcher/block_getter.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
https://github.com/omgnetwork/elixir-omg/issues/1557
Fixing the order of booted dependencies and made some bootup synchronus instead of async.
- status.get endpoint has dependencies to underlying services like OMG.Watcher.BlockGetter, OMG.Watcher.ExitProcessor, OMG.State. These dependencies need to be available with the first status.get call (even if it's cache!). 
`mix test`
> prevent race condition for status cache

- apps/omg_child_chain/lib/omg_child_chain/sync_supervisor.ex
- apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
Increasing the restart strategy.
/
> restart strategy

- apps/omg_watcher/lib/omg_watcher/block_getter/supervisor.ex
- apps/omg_watcher/lib/omg_watcher/configuration.ex
- config/config.exs
- config/test.exs
- docs/details.md
Reducing the aggressiveness of blockgetter.
- Timers per global block issuance rate. 8seconds.
> global block get interval

- apps/omg/lib/omg/state/transaction/payment/builder.ex
- apps/omg/lib/omg/wire_format_types.ex
- apps/omg_watcher_info/lib/omg_watcher_info/api/transaction.ex
- apps/omg_watcher_info/lib/omg_watcher_info/utxo_selection.ex
- apps/omg_watcher_rpc/lib/web/validators/order.ex
- apps/omg_watcher_rpc/lib/web/validators/typed_data_signed.ex
- apps/omg_watcher_rpc/priv/swagger/info_api_specs.yaml
- priv/cabbage/apps/itest/lib/client.ex
- priv/cabbage/apps/itest/test/features/payment_v2.feature
- priv/cabbage/apps/itest/test/itest/payment_v2_test.exs
- priv/cabbage/apps/itest/test/itest/transactions_test.exs
- priv/dev-artifacts/fee_specs.dev.json
:clipboard: closes https://github.com/omgnetwork/new-tx-type-poc/issues/16
Though the main goal is to be a bit TDD so have e2e test. However, without making change to existing code base it would not be able to run the test. I did try to make some minimum change to just let it work. 
There are separate issue tracking the implementation to make the code looks better.
Exit event testing is out of scope of this PR. It is also waiting on https://github.com/omgnetwork/elixir-omg/pull/1573
- Add payment v2 transfer cabbage test.
- watcher info `/transaction.create` now accept `tx_type` as a param (optional).
- Add payment v2 tx type and output type.
Add cabbage test. run `mix test test/itest/payment_v2_test.exs`
> cabbage test for payment v2

- apps/omg_watcher_info/lib/omg_watcher_info/db/eth_event.ex
This function is used in other traced functions in the same module so
errors appear:
```
2020-07-13 15:08:47.614 [error] module=Spandex function=start_trace/2
trace_id=31645604945997287 span_id=8193285015445073632 ⋅Tried to start
a trace over top of another trace.⋅
2020-07-13 15:08:47.634 [error] module=Spandex function=finish_trace/1
trace_id=4830626519991268780 span_id=5830755077416789889 ⋅Tried to
finish a trace without an active trace.
```
Because the function is decorated twice. get/1 is used only inside of
other traced functions and in tests.
> remove trace decorator from OMG.WatcherInfo.DB.EthEvent.get/1

- apps/omg/lib/omg/state/transaction/witness.ex
- apps/omg/test/omg/state/transaction/recovered_test.exs
- apps/omg/test/omg/state/transaction/witness_test.exs
Closes https://github.com/omgnetwork/elixir-omg/issues/1158
Fixes a crash when given an array of array of RLP encoded signatures.
> Add missing clause on witness validation check

- README.md
Extend description of running cabbage tests.
:heavy_check_mark: Requires https://github.com/omgnetwork/specs/pull/2 to be merged first. [commit](https://github.com/omgnetwork/specs/commit/96d67f4e065aad020dfde111419e95e397f443e8)
> docs: extend description of running cabbage tests

- .gitmodules
- apps/omg_child_chain/lib/omg_child_chain/fees/json_single_spec_parser.ex
- apps/omg_child_chain/test/omg_child_chain/fees/json_single_spec_parser_test.exs
- docker-compose.yml
pegged amount now can be decimal point, we add that and also enable `pegged` type
- remove `integer` validation on `validate_optional_positive_amount`
- add default value for fee interval fetching
- run test normally
> Fix fee adapter to accept decimal value in fee rules

- README.md
- docker-compose.yml
On the latest master I can't start reorg docker-compose locally, because it fails with the childchain is not healthy error:
```
Creating elixir-omg_postgres_1 ... done
Creating elixir-omg_geth_1     ... done
Creating geth-1                ... done
Creating geth-2                ... done
Creating nginx                 ... done
Creating childchain            ... done
ERROR: for watcher  Container "d7e5a929f9d7" is unhealthy.
ERROR: for watcher_info  Container "d7e5a929f9d7" is unhealthy.
```
I increased timeouts for childchain healthchecks. After that docker-compose starts without issues.
- Increase the timeouts for childchain healthchecks
- Use localhost in healthchecks
- Add reorg tests to the README
> chore: increase timeouts for childchain healthchecks

- apps/omg_watcher/lib/omg_watcher/api/account.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
Solves omgnetwork/private-issues#41
Assuming standard IFE case where in-flight transaction is not submitted. This means transaction's outputs don't exist and inputs regardless transaction's canonicity cannot be standard-exited. Therefore they are being filtered from the result of the `account.get_exitable_utxos` endpoint 
Inputs of the transaction in-flight are being removed from the results returned by the `account.get_exitable_utxos` endpoint 
Specs test demonstrate the feature https://github.com/omgnetwork/specs/pull/4
> account.get_exitable_utxos is unaware of in-flight exited inputs

- .circleci/ci_increase_chart_version.sh
- .circleci/config.yml
:clipboard: https://github.com/omgnetwork/releases/issues/23
Provide a CircleCI job that will trigger auto chart version increase PR after docker images are published successfully.
- Add a script to trigger Github action on helm-development repo
- Hook the script to CircleCI job with release tag filter
- [outside the PR] Have set `GITHUB_API_TOKEN` in circle ci env var manually
Done via playground repo and commenting out other jobs (so test the hook only). Here are the testing releases in the playground repo: https://github.com/omgnetwork/elixir-omg-boolafish-playground/releases
- example version bumping jobs: [here](https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg-boolafish-playground/34/workflows/fc8f82a3-a514-4b77-9659-cbb46b2a0b39)
- example result auto version bumping …
> auto trigger chart version bump

- apps/omg/lib/omg/state.ex
- apps/omg/lib/omg/state/core.ex
- apps/omg/test/omg/state/core_test.exs
- apps/omg/test/omg/state_test.exs
- apps/omg_child_chain/lib/omg_child_chain/block_queue.ex
- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_child_chain/lib/omg_child_chain/configuration.ex
- apps/omg_child_chain/lib/omg_child_chain/sync_supervisor.ex
- apps/omg_child_chain/test/omg_child_chain/block_queue/core_test.exs
- apps/omg_watcher/lib/omg_watcher/api/status_cache/external.ex
- apps/omg_watcher/lib/omg_watcher/block_getter.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- config/config.exs
Fixes https://github.com/omgnetwork/private-issues/issues/77
Allows to shorten the time for next block submission (which is not based on mined Ethereum blocks count) when there is enough pending transaction collected already.
Pending transaction count which triggers blocks submission can be configured by `BLOCK_SUBMIT_WHEN_N_TXS` environment variable.
When not set it defaults to _infinity_ which effectively switch off the feature.
Added 2 more Childchain's configuration properties and pass them down to the `BlockQueue` module.
- submit_block_when_n_txs
- block_fulfillment_check_interval_ms
When `submit_block_when_n_txs` is set to a number it will set a timer checking pending transactions count in the interval of `submit_block_when_n_txs` milliseconds. Timer will trigger block forming and …
> Verity: trigger block submit when enough pending txs

- .circleci/config.yml
- .gitmodules
resolves https://github.com/omgnetwork/elixir-omg/issues/1740
This PR parallelize feature tags using module tags with circle ci parallelism (https://circleci.com/docs/2.0/parallelism-faster-jobs/)
> Chore: parallelize tests by tags

- .github/workflows/enforce-changelog-labels.yml
- docker-compose.feefeed.yml
Fixes the issue where the label checker blocks the build from passing because all the build statuses are reset on a PR push and the label checker didn't get re-triggered.
- Enable PR label check on PR synchronize and reopen.
1. Create a PR
2. Label the PR with a supported label, e.g. `chore`
3. The `enforce-changelog-label` job should run and pass
4. Push a new commit to the PR
5. The `enforce-changelog-label` job should rerun and pass
> fix: recheck PR label on synchronize and reopen

- .circleci/config.yml
- Makefile
- apps/omg_eth/test/support/dev_geth.ex
- priv/perf/Dockerfile
- priv/perf/Makefile
This PR adds publishing of the perf project docker image to docker hub during circle ci builds so the perf project can be used as a standalone application outside of elixir-omg.
> Publish the perf project

- .circleci/config.yml
This PR adds ci step that runs `transactions` perf test
> add perf cli smoke test

- apps/omg_watcher_info/test/omg_watcher_info/pending_block_processor_test.exs
Gold team closing #1428 too aggressive test
https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/8948/workflows/ebcef81a-c492-4f05-adda-ec4860291272/jobs/87658
```
1) test handle_info/2 processes the next pending block in queue (OMG.WatcherInfo.PendingBlockProcessorTest)
apps/omg_watcher_info/test/omg_watcher_info/pending_block_processor_test.exs:41
Found message matching {:trace, ^pid, :receive, :timeout} after 200ms.
This means the message was delivered too close to the timeout value, you may want to either:
1. Give an increased timeout to `assert_receive/2`
2. Increase the default timeout to all `assert_receive` in your
test_helper.exs by setting ExUnit.configure(assert_receive_timeout: ...)
code: assert_receive {:trace, ^pid, :receive, :timeout}
stacktrace: …
```
> bug: aggressive test fix

- priv/perf/apps/load_test/lib/service/datadog/api.ex
in https://github.com/omgnetwork/elixir-omg/commit/dcc2d3d05383531ececef79020c266d112fb1438 datadog metrics were introduced.
Datadog api is timing out during ci runs sometimes
https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/8969/workflows/bdf890f7-2cd8-435e-81d7-8c4519e153d4/jobs/88002
> retry datadog errors

- apps/omg_status/lib/omg_status/metric/telemetry.ex
Currently the service name is part of the prefix for metrics, but it
would be far better if it were a tag, so that services could be compared
side by side in Datadog.
Rename the prefix to 'elixir'.
- Move the service name from being part of the prefix in the name of a metric to a tag on the metric.
```
docker-compose -f docker-compose-watcher.yml -f docker-compose.dev.yml up
﻿make docker-update-watcher
make docker-update-watcher_info
```
Check that metrics appear as omg.phoenix. ... with the service as a tag in Datadog. And this has been tested.
> fix: set service name as a tag in metrics

- .circleci/config.yml
- .releaserc.yaml
Add Semitic release tool to elixir-omg. This will auto create release on commit to master.
See this for more detail: https://omisego.atlassian.net/wiki/spaces/ENG/pages/937918471/Releases+of+a+git+repo
- add the tool to circle ci
- currently in dry-run mode. I am slightly concerned on initial tag creation as we got old tags existing.
messed around on my playground repo
- dry-run result: https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg-boolafish-playground/142/workflows/da8a2fb3-071b-4431-bc0b-268c22c5b237/jobs/470
- non dry-run tagged: https://github.com/omgnetwork/elixir-omg-boolafish-playground/releases/tag/v1.0.1
> chore: add sem release automation

- .releaserc.yaml
> This run was triggered by a pull request and therefore a new version won't be published.
Observed this from this: [job](https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/9170/workflows/c3cfc660-7833-4f23-a247-204fd427e2e3/jobs/90895)
set ci check to false, following this: https://github.com/semantic-release/semantic-release/issues/1074#issuecomment-696922883
N/A, waiting the merge to run the dry-run
> fix: make sem release ignore PR check

- .circleci/config.yml
VERSION file is not used and was removed in https://github.com/omgnetwork/elixir-omg/pull/1798/files
Because of `lint_version` step, helm development jobs are failing - https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/9316/workflows/eac99138-db86-4c72-b551-8ae6d44b505f
> remove lint version
