omgnetwork/elixir-omg

- README.md
- apps/omg_api/config/config.exs
- apps/omg_api/lib/api.ex
- apps/omg_api/mix.exs
- apps/omg_api/test/integration/fixtures.exs
- apps/omg_jsonrpc/lib/application.ex
- apps/omg_jsonrpc/lib/expose_spec.ex
- apps/omg_jsonrpc/lib/expose_spec/rpc_translate.ex
- apps/omg_jsonrpc/lib/exposer.ex
- apps/omg_jsonrpc/lib/jsonrpc.ex
- apps/omg_jsonrpc/lib/server.ex
- apps/omg_jsonrpc/mix.exs
- apps/omg_jsonrpc/test/expose_spec_test.exs
- apps/omg_jsonrpc/test/exposer_test.exs
- apps/omg_performance/lib/performance.ex
- apps/omg_performance/mix.exs
- apps/omg_watcher/mix.exs
- apps/omg_watcher/test/fixtures.exs
- docs/architecture.md
co-authored with @pgebal during refactor Friday
closes OMG-221
> OMG-221 - refactor: make omg_jsonrpc not dependent on omg_api

- apps/omg_api/test/state/core_test.exs
- apps/omg_watcher/lib/utxo_db.ex
- apps/omg_watcher/test/web/controllers/utxo_test.exs
This is a behavior emergent from our implementation. I'm not sure if it is a good idea to cover it with a unit test. Maybe we should document it instead.
> Add a test case covering lack of outputs and value set to zero

- Dockerfile
Adds support for builds as far as needing `geth`.
To build:
`docker build -t plasma .`
To run:
`docker run -ti plasma`
> [elixir-omg] Add Dockerfile

- apps/omg_eth/lib/eth/root_chain.ex
- apps/omg_eth/lib/eth/token.ex
before, they were overriden by the global defaults and deposits used @lots_of_gas
> fix: make default ethereum transaction defaults correct

- README.md
- docs/demo_02.md
it used to still use the empty passphrase
> docs: updated the demo and readme with new default passphrase

- apps/omg_eth/mix.exs
- mix.lock
Contracts stays the same, its only a change of the branch name.
> Update contracts to point to release branch

- apps/omg_watcher/test/fixtures.exs
- apps/omg_watcher/test/web/controllers/transaction_test.exs
> test(watcher): cleaning test descriptions & one more test

- apps/omg_watcher/config/dev.exs
> Bumping postgres timeout to 60s

- apps/omg_api/lib/config.ex
- apps/omg_jsonrpc/lib/client.ex
- apps/omg_performance/lib/performance.ex
- apps/omg_watcher/config/config.exs
e.g. CHILD_CHAIN_URL="http://yourserver.com:9656"
> Provide some vars via env

- apps/omg_watcher/lib/web/controllers/status.ex
returned the validate/closed block number instead
> fix: prevent status returning the current block of State

- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/test/block_getter/core_test.exs
a subset of #252 which we decided to include in the release
> fix: allow margin in reading submissions on BlockGetter start

- README.md
- apps/omg_api/lib/state/core.ex
- apps/omg_api/test/state/core_test.exs
- apps/omg_watcher/lib/eventer/event.ex
- apps/omg_watcher/test/integration/block_getter_test.exs
- apps/omg_watcher/test/integration/invalid_exit_test.exs
> OMG-337 fix: add child_txindex to address_spent/received events

- docs/exit_validation.md
note the Diagram linked inside the md file
> OMG-308 docs: add the whiteboarded diagram + description

- docs/morevp.md
also expands and tidies the alicebobbings somewhat
> OMG-346 docs: add known issue of retries/timeouts to morevp.md

- launcher.py
Adds support for Watcher zero touch deployments.
Pushing before `develop` gets deprecated in favour of OIP4.
> [elixir-omg] Add support for zero touch Watcher deployments

- apps/omg_db/lib/db.ex
- apps/omg_db/lib/leveldb_core.ex
- apps/omg_db/lib/leveldb_server.ex
removes repetitive code, makes adding new  entities more consistent and adds IFE support
> Leveldb refactor

- launcher.py
- Fixes Watcher deployment on Rinkeby
- Tidy some NOQA statements for PEP8
- Remove redundant logging
> [launcher] Fix Watcher config.exs write from pre-deployed contract

- apps/omg_api/lib/state/core.ex
- apps/omg_api/test/state/core_test.exs
- apps/omg_db/lib/db.ex
- apps/omg_db/lib/leveldb_core.ex
- apps/omg_db/lib/leveldb_server.ex
- apps/omg_performance/lib/sender_server.ex
- apps/omg_watcher/lib/api/utxo.ex
- apps/omg_watcher/lib/challenger.ex
- apps/omg_watcher/lib/challenger/core.ex
- apps/omg_watcher/lib/db/transaction.ex
- apps/omg_watcher/test/challenger/core_test.exs
- apps/omg_watcher/test/db/transaction_test.exs
- apps/omg_watcher/test/web/controllers/challenge_test.exs
Proof of concept to show we can base security critical Watcher on OMG.DB
> Omg 328 add spend set to omgdb

- apps/omg_watcher/config/config.exs
- apps/omg_watcher/lib/web/sockets/endpoint.ex
- apps/omg_watcher/mix.exs
- mix.lock
> feat: enable CORS, configurable, enabled by default

- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/test/block_getter/core_test.exs
> fix: allow BlockGetter to work on 1-scheduler machines

- docker-compose.yml
- Fixes the timeout with the Childchain startup
- Fixes the geth healthcheck
> fix: Increase childchain healthcheck timeout & fix geth

- docker-compose-non-mac.yml
- docker-compose.yml
Really fix it this time - previous effort put CHILDCHAIN_URL in the wrong place 🤦‍♂️
> Fix docker-compose.yml watcher env (again)

- apps/omg_watcher/config/config.exs
> feat: Get Ecto telemetry into AppSignal

- apps/omg_watcher/config/config.exs
- apps/omg_watcher/config/dev.exs
- apps/omg_watcher/config/prod.exs
> fix: Move AppSignal loggers to correct location for dev and prod

- .circleci/config.yml
Remove geth from testing image
> feat: More tidying of CI test image

- docker-compose-non-mac.yml
Tested on Ubuntu 18.10 Docker 18.09.1
> fix: Fix docker-compose for Linux

- apps/omg_api/lib/state/transaction.ex
- apps/omg_api/lib/state/transaction/signed.ex
- apps/omg_db/lib/leveldb_core.ex
- apps/omg_watcher/lib/exit_processor.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/web/controllers/transaction_test.exs
- config/.credo.exs
rather unrelated fixes. The main flakiness-related thing is the timeout, but nothing that could've really solved the `:not_found` problem as in [here](https://circleci.com/gh/omisego/elixir-omg/752) for example.
> Fix block getting flakiness and other

- apps/omg_api/lib/application.ex
- apps/omg_api/test/state/core_test.exs
- apps/omg_eth/lib/eth/root_chain.ex
- apps/omg_watcher/lib/api/status.ex
- apps/omg_watcher/lib/application.ex
- apps/omg_watcher/lib/challenger/challenge.ex
- apps/omg_watcher/lib/challenger/core.ex
- apps/omg_watcher/lib/exit_processor.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/lib/web/router.ex
- apps/omg_watcher/lib/web/views/in_flight_exit.ex
- apps/omg_watcher/priv/swagger/watcher_api_specs.yaml
- apps/omg_watcher/test/challenger/core_test.exs
- apps/omg_watcher/test/exit_processor/core_test.exs
- apps/omg_watcher/test/integration/block_getter_test.exs
- apps/omg_watcher/test/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/integration/invalid_exit_test.exs
- apps/omg_watcher/test/support/test_helper.ex
- apps/omg_watcher/test/web/controllers/challenge_test.exs
- apps/omg_watcher/test/web/controllers/transaction_test.exs
- docs/demo_02.md
- docs/demo_04.md
- docs/in_flight_exit_scenarios.md
- docs/unified_api.md
clear distinction between utxo_pos and output_index
should be rather merged after: https://github.com/omisego/plasma-contracts/pull/59
> style: change naming convention in order to stick to the contract

- apps/omg_rpc/test/fixtures.exs
- apps/omg_watcher/lib/block_getter.ex
- apps/omg_watcher/lib/block_getter/core.ex
- apps/omg_watcher/lib/event.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/block_getter/core_test.exs
- apps/omg_watcher/test/integration/block_getter_test.exs
as title + some necessary refactors and tidies - refer to individual commits to shed more light, their rather orthogonal
> Omg 369 challenge the unchallengable

- apps/omg_api/lib/ethereum_event_listener.ex
- apps/omg_api/lib/ethereum_event_listener/core.ex
- apps/omg_api/lib/root_chain_coordinator/core.ex
- apps/omg_api/test/ethereum_event_listener/core_test.exs
- apps/omg_api/test/root_chain_coordinator/core_test.exs
as title + includes a more stringent handling of the height update checks in root chain coordinator, cherrypicked from 25999b1247003c01bdf58c7d90fa783f1d489ad6
> Omg 386 fix ethlistener corrupt state

- apps/omg_watcher/lib/web/views/error_view.ex
Note to reviewer: Unfortunately cannot add test to show the feature. Firstly because of Sentry failure: #437 
Switching off Sentry, there is still unhandled exception from Poison while deserializing requiest which pops up and kills test endpoint. Manual testing is required, running Watcher process. 
Closes #416
> OMG-395 - [github] invalid json requests grill the http-rpc APIs 

- docker-compose-non-mac.yml
- docker-compose.yml
Custom exit period for deploying contracts locally
> feat: Add support for custom exit times in docker-compose

- .circleci/config.yml
- apps/omg_watcher/test/support/integration/test_server.ex
- dialyzer.ignore-warnings
- mix.exs
This reduces the whole dev build from 19 mins to 10 mins.
It also gives quick feedback by parallel test execution.
> concurrent jobs

- apps/omg_api/config/config.exs
- apps/omg_api/lib/ethereum_event_listener.ex
- apps/omg_api/lib/root_chain_coordinator/core.ex
- apps/omg_eth/config/config.exs
- apps/omg_watcher/lib/block_getter.ex
also add some introspection around handling of queries that are dangerously lengthy
> fix: prefer more frequent and smaller queries for events

- apps/omg_watcher/lib/exit_processor.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
- apps/omg_watcher/test/integration/in_flight_exit_test.exs
- docs/api_specs/status_events_specs.md
> fix: fix reporting unavailable piggyback as available

- launcher.py
Adds the logic from development into staging and Ari. The Watcher will not resync if there is data present.
> feat: Add Watcher preservation of data to staging and Ari

- apps/omg_api/config/config.exs
- apps/omg_api/lib/sup.ex
- apps/omg_api/mix.exs
- apps/omg_watcher/lib/application.ex
- apps/omg_watcher/lib/web/endpoint.ex
- dialyzer.ignore-warnings
- mix.lock
I think it was agreed to remove it.
> refactor: removing sentry as dependency

- apps/omg_api/lib/state/core.ex
- apps/omg_api/lib/utxo.ex
- apps/omg_watcher/lib/exit_processor/competitor_info.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/lib/exit_processor/exit_info.ex
- apps/omg_watcher/lib/exit_processor/in_flight_exit_info.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
- apps/omg_watcher/test/exit_processor/persistence_test.exs
review only the fix at https://github.com/omisego/elixir-omg/commit/31ac10b46d02fd05df6f5f8b519b8bced5364870
The other commit is a revert.
They both are intended to fix issues that surfaced on staging
> Omg 420 fix "tx seen in blocks at" issue

- docker-compose-non-mac.yml
- docker-compose.yml
- docs/manual_service_startup.md
> docs: set targetgaslimit when starting dev geth

- apps/omg_api/lib/ethereum_client_monitor.ex
- apps/omg_api/lib/ethereum_event_listener.ex
- apps/omg_api/test/block_queue/core_test.exs
- apps/omg_api/test/ethereum_client_monitor_test.exs
- apps/omg_watcher/lib/alert/alarm.ex
- apps/omg_watcher/lib/alert/alarm_handler.ex
- apps/omg_watcher/lib/application.ex
- apps/omg_watcher/lib/coordinator_setup.ex
- apps/omg_watcher/lib/supervisor.ex
- apps/omg_watcher/lib/sync_supervisor.ex
- apps/omg_watcher/test/supervisor_test.exs
This adds the custom monitoring of the ethereum client connectivity as we've introduced to childchain.
> Omg 419 client connectivity watcher

- apps/omg_api/lib/state/transaction.ex
- apps/omg_api/lib/state/transaction/recovered.ex
- apps/omg_api/test/api/core_test.exs
- apps/omg_api/test/state/core_test.exs
- apps/omg_api/test/state/transaction_test.exs
- apps/omg_watcher/test/exit_processor/core_test.exs
- docs/transaction_validation.md
This is __part one__ of the task - provides fix for child chain, there will be also fix for plasma contract repo.
The idea of the fix is to stop improperly constructed transactions leak into the system and make them invalid while transaction is decoded from RLP.
> Omg 399 illegality of tx with holes - #1

- apps/omg/lib/state/transaction/recovered.ex
- apps/omg/lib/state/transaction/signed.ex
- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
Otherwise, it does too much checking, while the transactions submitted as IFE may hold spurious signatures for zero-inputs
> fix: make spender getting not use Transaction.Recovered.recover_from

- apps/omg/lib/omg/fees.ex
- apps/omg/lib/omg/state/core.ex
- apps/omg/lib/omg/state/transaction.ex
- apps/omg/lib/omg/state/transaction/recovered.ex
- apps/omg/lib/omg/utxo/position.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
- apps/omg_watcher/test/omg_watcher/web/controllers/in_flight_exit_test.exs
> [OMG-403] transaction getters should filter out empty values

- docker-compose-non-mac.yml
- docker-compose.yml
Seems I was fooled while testing [this change](https://github.com/omisego/elixir-omg/commit/cdea6d8c38c3888845e2936dbea0fcd3221630e9#diff-4e5e90c6228fd48698d074241c2ba760) by my local postgres instance :man_facepalming:
> changed dockerized watcher database port

- apps/omg/lib/omg/recorder.ex
- apps/omg_api/lib/omg_api/application.ex
- apps/omg_api/lib/omg_api/ethereum_client_monitor.ex
- apps/omg_api/test/omg_api/alert/alarm_test.exs
- apps/omg_api/test/omg_api/ethereum_client_monitor_test.exs
- apps/omg_db/lib/omg_db/recorder.ex
- apps/omg_status/lib/omg_status/metric/recorder.ex
- apps/omg_watcher/lib/omg_watcher/application.ex
- apps/omg_watcher/lib/omg_watcher/recorder.ex
- docker-compose-non-mac.yml
- docker-compose.yml
This is a wip in order to start the discussion:
- how to handle cookies
- how to distinguish deployment environments
> feature: introspection of development env

- apps/omg_watcher/lib/exit_processor/core.ex
- apps/omg_watcher/test/exit_processor/core_test.exs
- apps/omg_watcher/test/web/controllers/in_flight_exit_test.exs
> fix: handle malformed txbytes as inputs to IFE-related endpoints

- launcher.py
Not cherry picking as there's been a few PRs
> feat: Add migrations to v0.1 launcher

- launcher.py
per @jbunce's request cherrypicking #606 to `v0.1`
> feat: Add AppSignal deployment marker to launcher.py

- apps/omg_watcher/lib/omg_watcher/db/transaction.ex
- apps/omg_watcher/priv/repo/migrations/20190408131000_add_missing_indices_to_txoutputs.exs
- apps/omg_watcher/test/omg_watcher/db/transaction_test.exs
- apps/omg_watcher/test/omg_watcher/web/controllers/transaction_test.exs
cherrypicking from #596 + some comments on testing
> cherrypick fix transaction all

- launcher.py
- Fixes support for the Childchain
- Adds support for the Watcher
- PEP8 compliant
> fix: Support Gorli contracts & add support for the Watcher

- .circleci/config.yml
- apps/omg_api/test/integration/happy_path_test.exs
- apps/omg_performance/test/performance_test.exs
- apps/omg_watcher/test/integration/block_getter_test.exs
- apps/omg_watcher/test/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/integration/invalid_exit_test.exs
- apps/omg_watcher/test/web/controllers/status_test.exs
Same changes as in master, parallel builds and test compilation caching!
> fix: porting circleci configuration

- apps/omg_api/lib/application.ex
- apps/omg_status/lib/status/metric/recorder.ex
- apps/omg_watcher/lib/application.ex
- docker-compose-non-mac.yml
- docker-compose.yml
Introspection ported from master.
> fix: porting introspection

- launcher.py
Adding support for Gorli to v0.1
> fix: Add Gorli to v0.1

- mix.exs
since v0.1.4:
Merge pull request #592 from omisego/591_malformed_txs_for_IFEs
Merge pull request #596 from omisego/589-fix-transaction-all
Merge pull request #600 from omisego/add_migration_to_launcher
Merge pull request #612 from omisego/cherry_pick_add_depl_marker
Merge pull request #607 from omisego/601-status-content-type
Merge pull request #604 from omisego/refactor-swagger-doc
Merge pull request #641 from omisego/fix_spend_not_found
Merge pull request #661 from omisego/parallel_builds
Merge pull request #664 from omisego/enable_introspection
Merge pull request #669 from omisego/update_launcher
> bump version to v0.1.5

- apps/omg_performance/lib/performance.ex
It seems the errors happened when omg_performance "simple perftest" tests ran.
After changes from cd094b589a6881cc38696dc7006c792a6b1415c5 we started ramping up the whole :omg_child_chain, including the Ethereum-machinery.
This machinery complained about the ethereum configs being malformed.
This proposes to revert to the selective start approach prior to the mentioned change, including some readability and doc improvements.
NOTE: to reproduce the odd length string error, tag `happy_path_test` and `performance_test` with `tag: :this` and do:
```
mix test --only this --seed 294090
```
> fix: make odd length string errors go away

- apps/omg/test/omg/state/persistence_test.exs
- apps/omg_db/config/config.exs
- apps/omg_db/lib/db.ex
- apps/omg_db/lib/omg_db/application.ex
- apps/omg_db/lib/omg_db/ets.ex
- apps/omg_db/lib/omg_db/level_db.ex
- apps/omg_db/lib/omg_db/leveldb/core.ex
- apps/omg_db/lib/omg_db/leveldb/recorder.ex
- apps/omg_db/lib/omg_db/leveldb/server.ex
- apps/omg_db/test/fixtures.exs
- apps/omg_db/test/omg_db/db_test.exs
- apps/omg_db/test/omg_db/recorder_test.exs
- apps/omg_db/test/support/level_db_case.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
Issue: https://github.com/omisego/elixir-omg/issues/628
The idea behind the PR is to provide a set of behavioral patterns that specific database implementation needs to follow so that we're able to plug whatever we would like to test out.
> refactor: db abstraction

- apps/omg_db/config/config.exs
> leveldb default

- apps/omg_watcher/lib/omg_watcher/web/views/transaction.ex
- apps/omg_watcher/priv/swagger/informational_api_specs.yaml
- apps/omg_watcher/priv/swagger/schemata.yaml
- apps/omg_watcher/test/omg_watcher/web/controllers/transaction_test.exs
> Add metadata to `transaction.get` endpoint output

- launcher.py
Deployments with Infura as the Ethereum connectivity backend fail as the client version RPC call is not available. This PR skips that check.
> feat: Add support to launcher.py for Infura

- apps/omg_child_chain/lib/omg_child_chain/block_queue.ex
- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_eth/test/support/dev_geth.ex
porting: "Merge pull request #685 from omisego/block_queue_error_diagnostics" to `master`
> feat: improve error logs when BlockQueue has problems, ports #685

- .circleci/config.yml
> fix: Update CircleCI for development Samrong

- apps/omg_watcher/lib/omg_watcher/block_getter.ex
- apps/omg_watcher/lib/omg_watcher/coordinator_setup.ex
- apps/omg_watcher/test/omg_watcher/supervisor_test.exs
Ports #701 and #704 from `v0.1`
> Port 701 704 from v0.1

- .circleci/config.yml
- Dockerfile.child_chain
- Dockerfile.watcher
- Makefile
https://github.com/omisego/elixir-omg/issues/579
A merge to master - and temporary my wip branches should publish a new docker image bundled with a OTP release that you can use - standalone or in a regular deployment (that part is WIP)
- Made the scripts use arguments which image it should publish.
Goes through CI if the branch is master (or my branch while I keep on working on it).
> 579 publish release docker p2

- README.md
Answering the question from discussion in #734
as title, added some contents to `README.md` to explain
N/A
N/A
> docs: explain nonces restriction (nonces problem) in docs

- apps/omg_rpc/priv/swagger/operator_api_specs/transaction/paths.yaml
- apps/omg_rpc/priv/swagger/operator_api_specs/transaction/request_bodies.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/account/paths.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/account/request_bodies.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/account/response_schemas.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/account/responses.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/account/schemas.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/transaction/paths.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/transaction/request_bodies.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/transaction/response_schemas.yaml
- apps/omg_watcher/priv/swagger/informational_api_specs/transaction/schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/account/paths.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/account/request_bodies.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/account/response_schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/account/responses.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/account/schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/in_flight_exit/paths.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/in_flight_exit/request_bodies.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/status/response_schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/status/schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/swagger.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/transaction/paths.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/transaction/request_bodies.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/transaction/schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/utxo/paths.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/utxo/request_bodies.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/utxo/response_schemas.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/utxo/responses.yaml
- apps/omg_watcher/priv/swagger/security_critical_api_specs/utxo/schemas.yaml
:clipboard: Closes #727 
Review API specification for correctness and compliance with v0.2 (Samrong). As far as I know master HEAD is (will be) cherry picked to v0.2 branch (when final) therefore can be merged into master.
As discussed with @Pongch v0.2 testnet address is not revealed in servers dropdown.
Updated requests and response schemata and examples. Added missing endpoints.
Swagger specs rebuild and deployed into [0.2](https://developer.omisego.co/elixir-omg/) folder.
> 727 api compliance with v02

- README.md
- docs/run_local_watcher.md
> docs: document that docker-compose 1.24 works but 1.17 might not

- launcher.py
As title
reverting change from yesterday
> fix: Remove --no-start from mix ecto.reset

- launcher.py
> fix: Revert removal of --no-start

- .circleci/config.yml
Fixes bash statement
sleep(120) -> sleep 120
Locally tested
> fix: f you bash

- apps/omg_child_chain_rpc/config/config.exs
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/endpoint.ex
- apps/omg_child_chain_rpc/mix.exs
- apps/omg_child_chain_rpc/test/support/web/test_helper.ex
- apps/omg_watcher/test/support/test_helper.ex
https://github.com/omisego/elixir-omg/issues/782
https://github.com/omisego/devops/issues/94
Enabled CORS on child chain and enables tests for CORS headers.
Added dependency to child_chain_rpc app and enabled tests on all controllers.
/
> 782 ch cors

- .circleci/config.yml
> fix: Bash syntax

- .circleci/config.yml
If this doesn't work we're putting the sleep statement back in.
curl test runner
Local shell
> fix: Finally fix this condition

- README.md
:clipboard: https://github.com/omisego/elixir-omg/pull/793
Update the README to provide the correct `docker-compose` commands
* `README` update to provide up to date `docker-compose` instructions
N/A
> update docker-compose directions in README

- mix.exs
> chore: bump version to v0.1.6

- README.md
Asked on our slack
adds a short explanation on how do the two modes differ
-
:eyes:
> docs: document the two modes of the watcher in README.md

- apps/omg_utils/lib/omg_utils/http_rpc/response.ex
- apps/omg_watcher/test/support/test_helper.ex
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/enforce_content_plug_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs
:clipboard: #805
API response shows OMG network version (matched to the `major.minor` [semver](https://semver.org/))
Changed standard response version field value.
Unit tested
> 805 api response version master

- apps/omg/config/config.exs
- apps/omg/lib/omg/application.ex
- apps/omg/lib/omg/ethereum_event_listener.ex
- apps/omg/lib/omg/recorder.ex
- apps/omg/lib/omg/state.ex
- apps/omg/lib/omg/state/core/metrics.ex
- apps/omg/test/omg/state/core/metrics_test.exs
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/transaction.ex
- apps/omg_child_chain_rpc/test/test_helper.exs
- apps/omg_db/lib/omg_db/leveldb/recorder.ex
- apps/omg_db/lib/omg_db/rocksdb/recorder.ex
- apps/omg_status/lib/omg_status/metric/recorder.ex
- apps/omg_utils/lib/omg_utils/metrics.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor.ex
- apps/omg_watcher/lib/omg_watcher/recorder.ex
- apps/omg_watcher_rpc/lib/web/controllers/transaction.ex
- mix.exs
- mix.lock
:clipboard: https://github.com/omisego/elixir-omg/issues/549
move application metrics from `AppSignal`(https://github.com/omisego/elixir-omg/pull/640) to `DataDog`
See Notebook list in DataDog.
> feat: watcher application metrics use datadog

- apps/omg_performance/lib/omg_performance/sender_manager.ex
- docs/perf_test_result_dumps.md
https://github.com/omisego/elixir-omg/issues/832
Kernel round instead of Float
Standard testing.
> fix: use Kernel round instead of Float round

- apps/omg_child_chain_rpc/config/config.exs
- apps/omg_child_chain_rpc/config/dev.exs
- apps/omg_child_chain_rpc/config/test.exs
- apps/omg_watcher_rpc/config/config.exs
- apps/omg_watcher_rpc/config/dev.exs
- apps/omg_watcher_rpc/config/test.exs
- rootfs/child_chain_entrypoint
https://github.com/omisego/elixir-omg/issues/579
Startup sequence of a release needs KV init.
- Also removed unused secrets for cookie signing. (THere's no cookies)
> feature: init kv db and start

- apps/omg/lib/omg/ethereum_client_monitor.ex
- apps/omg/lib/omg/ethereum_height.ex
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/web/plugs/health_test.exs
Correct maching on endpoint return
PR from @pthomalla pointed out that the test wasn't matching on the correct endpoint return value.
Same tests apply.
> fix: matching endpoint return

- apps/omg_child_chain/test/omg_child_chain/integration/fee_server_test.exs
``` 
* test fees in effect corrupted file does not make server crash (1128.5ms)
2019-07-23 08:15:32.403 [error] module=OMG.ChildChain.FeeServer function=update_fee_spec/0 ⋅Unable to update fees from file. Reason: {:error, %Jason.DecodeError{data: "[not a json]", position: 1, token: nil}}⋅
1) test fees in effect corrupted file does not make server crash (OMG.ChildChain.Integration.FeeServerTest)
test/omg_child_chain/integration/fee_server_test.exs:60
Assertion with =~ failed
code:  assert refresh_fees() =~ ~r"\\[error\\].*Unable to update fees"
left:  ""
right: ~r/\[error\].*Unable to update fees/
stacktrace:
test/omg_child_chain/integration/fee_server_test.exs:70: (test)
```
> fix: fix flaky test

- Makefile
- mix.exs
> fix: fetch release version from file

- docs/api_specs/status_events_specs.md
- docs/exit_validation.md
Answers requests to document on our slack
Provides details as in title
N/A
:eyes: :book: :scroll:
> docs: add more details and rationale on the `unchallenged_exit` event

- apps/omg/test/omg/integration/root_chain_coordinator_test.exs
- apps/omg_child_chain/lib/omg_child_chain/supervisor.ex
- apps/omg_child_chain/test/omg_child_chain/integration/fee_server_test.exs
- apps/omg_child_chain/test/omg_child_chain/integration/monitor_test.exs
- apps/omg_child_chain_rpc/test/fixtures.exs
- apps/omg_eth/lib/omg_eth/supervisor.ex
- apps/omg_eth/test/omg_eth/ethereum_client_monitor_test.exs
- apps/omg_status/test/omg_status/integration/alarms_test.exs
- apps/omg_status/test/omg_status/metric/statsd_monitor_test.exs
- apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
- apps/omg_watcher/test/omg_watcher/api/alarm_test.exs
Fix integration test 
- correctly closing omg_status at the end of the test
- corrected alias Alert.Alarm
mix test --only integration
> test: fix running integration tests

- .circleci/config.yml
Overview
`run mix test --only integration every week day at 15:15 UTC.`
- Circle nightly flow
/
> Run integration ci

- .circleci/config.yml
> fix: cleanup config

- apps/omg_watcher/test/omg_watcher/exit_processor/standard_exit_test.exs
fixes https://github.com/omisego/devops/issues/127
Adds a test that caused the incident [2019-08-26 – Samrong byzantine condition](https://github.com/omisego/devops/issues/127) (**private link** :( ), where valid SEs in the presence of totally unrelated IFEs were triggered as invalid. Bug due to broken and unclear use of truthy/Enum.find, unclarity not present anymore in `v0.2`/`master`
No fix required because the bug introduced in https://github.com/omisego/elixir-omg/commit/f2d9e5f4f773a151797f3bcd3e7240f3188a536e#diff-8aed61245222c08806d5d041c8fb2199R193
already fixed in https://github.com/omisego/elixir-omg/blob/v0.2/apps/omg_watcher/lib/omg_watcher/exit_processor/standard_exit.ex#L204
add a test for the exact case that broke
`mix test`. Also one can backtrack to `v0.2.1`, add an …
> test: add missing test for the bug (IFE borking SEs) in v0.2.1

- .circleci/config.yml
https://github.com/omisego/elixir-omg/issues/908
Send manual events and entries to Datadog and Sentry but also notify Slack
- Add Datadog, Sentry and Slack integration in Circle CI
yolo
> feature: send out deployment markers

- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_child_chain/test/omg_child_chain/block_queue/core_test.exs
a request for docs on Slack
Putting down a technical description of the behavior of the mechanism.
Also added two tests during the process of figuring out whether the description matches the behavior.
see above
`mix test` and :eyes:
> docs: document gas price mechanics + add some tests for current behavior

- apps/omg_status/lib/omg_status/application.ex
- apps/omg_status/lib/omg_status/metric/vmstats_sink.ex
Fixes a previous less performant implementation
Fixes a previous less performant implementation by setting configuration tags.
> fix: global dd tags for metrics

- apps/omg_performance/lib/omg_performance/sender_manager.ex
- apps/omg_performance/lib/omg_performance/sender_server.ex
- apps/omg_performance/lib/performance.ex
https://github.com/omisego/elixir-omg/issues/923
Passing child chain url as an argument or as a env var was not honored  
- 
Test are already there. I just adapted them to new changes.
> fix: pass child chain URL

- apps/omg_eth/lib/eth.ex
- apps/omg_eth/lib/omg_eth/subscription_worker.ex
- apps/omg_eth/test/support/deployer.ex
- apps/omg_eth/test/support/librarian.ex
Sobelow run pointed out some issues with the code (none of them are security issues!)
/
Cleanup: use to_existing_atom/1 instead of to_atom and clenaup some unused functions (apart from tests)
- ...
/
> fix: to existing atoms and clenaup unused functions

- README.md
Updated testing docs regarding some gotchas...
> updated testing docs

- README.md
- docs/architecture.md
(Reviewing for the documentation site contd.)
Just the no-brainer fixes and updates I spotted when skimming through the docs. Only updates some clearly confusing pieces.
na
na
> docs: refresh README.md and architecture.md

- .circleci/config.yml
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/web/plugs/health_test.exs
- apps/omg_status/config/test.exs
- apps/omg_utils/lib/omg_utils/http_rpc/response.ex
- apps/xomg_tasks/lib/mix/tasks/watcher.ex
- bin/setup
A setup script that install all OS dependencies (currently tested only for linux distros).
- ./bin/setup should make a local environment ready for bare metal development.
checkout code + setup run + execute mix test.
Postgress installation is skipped because ... I think CircleCI doesn't allow creating users and roles manually.
> feature: local setup script

- apps/omg/lib/omg/state/core.ex
- apps/omg_eth/lib/eth.ex
- apps/omg_eth/lib/omg_eth/root_chain.ex
- apps/omg_eth/test/omg_eth/eth_test.exs
- apps/omg_watcher/lib/omg_watcher/db/eth_event.ex
- apps/omg_watcher/lib/omg_watcher/db/txoutput.ex
- apps/omg_watcher/priv/repo/migrations/20190806111817_alter_txoutputs_ethevents_make_many_to_many_relation.exs
- apps/omg_watcher/test/fixtures.exs
- apps/omg_watcher/test/omg_watcher/db/eth_event_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/account_test.exs
- docs/watcher_db_design.md
Change schema to have a many-to-many relationship between txoutputs and ethevents tables.
Manual testing done, but want to sanity check my PR. If it's in the right direction I'll add tests, otherwise I'll incorporate your comments. (Just don't want to waste time writing tests if you see major problems with the code).
For issue #801 
Change schema to have a many-to-many relationship between txoutputs and ethevents tables.
Manual testing using omg-js and creating various scenarios. Updated automated tests.
> 801 expose ethereum txns part 1

- .circleci/ci_deploy.sh
- .circleci/config.yml
https://github.com/omisego/elixir-omg/issues/579
Standardize application bootup #579 
CircleCI should be able to push a new development deployment
- Circleci steps + deployment script
/
> feature: deploy release

- .circleci/ci_deploy.sh
> Deploy fix

- .circleci/ci_deploy.sh
> fix: no need for gcp zone

- docs/deployment_configuration.md
First deployment and @kendricktan spotted some missing docs! thanks!!!
/
/
/
> feature: more docs

- .circleci/ci_deploy.sh
> fix: statefullset name

- apps/omg_watcher/priv/repo/migrations/20190806111817_alter_txoutputs_ethevents_make_many_to_many_relation.exs
> null: true, not null: false

- apps/omg_child_chain/lib/omg_child_chain/monitor.ex
- apps/omg_child_chain/test/omg_child_chain/integration/monitor_test.exs
- apps/omg_watcher/lib/omg_watcher/monitor.ex
- apps/omg_watcher/test/omg_watcher/integration/monitor_test.exs
https://github.com/omisego/elixir-omg/issues/988
Harden the test that was sometimes failing.
- I've merged two tests into one to avoid side affects
/
> fix: rewrite monitor test

- apps/omg_status/mix.exs
> feature: migrate statix to bleacherreport branch for events support

- .circleci/config.yml
0.1 is old production
0.2 is new production
for which we need CD staging.
> Deploy 0.2 branch

- apps/omg/lib/omg/state/measure.ex
/
Devops incident
https://github.com/omisego/elixir-omg/commit/db68d87611ce6f5080e93daf6dc43588b5966e77#diff-30d2b9d17e9d95a9bde5ab11a93404ab
/
> fix: copy UTXOs to Task

- Dockerfile.child_chain
- Dockerfile.watcher
- Makefile
Make RocksDB and Docker goes to fitness
Use a new slim builder during docker build :-) 
See also https://github.com/omisego-images/docker-elixir-omg/pull/2 
🤷‍♂
> refactor: slim rocksdb build

- .circleci/config.yml
- bin/setup
Slack raised issue and failed barebone build: https://app.circleci.com/jobs/github/omisego/elixir-omg/20131
Install rocksdb via git
- separate step in bin/setup
barebuild
> fix: install rocksdb from repo

- apps/omg/lib/omg/ethereum_event_listener.ex
- apps/omg_child_chain/lib/omg_child_chain/coordinator_setup.ex
- apps/omg_child_chain/lib/omg_child_chain/monitor.ex
- apps/omg_child_chain/lib/omg_child_chain/supervisor.ex
- apps/omg_child_chain/lib/omg_child_chain/sync_supervisor.ex
- apps/omg_child_chain/test/omg_child_chain/integration/monitor_test.exs
- apps/omg_child_chain/test/omg_child_chain/sup_test.exs
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/application.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/block.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/transaction.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/plugs/health.ex
- apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/router.ex
- apps/omg_db/mix.exs
- apps/omg_performance/lib/performance.ex
- apps/omg_status/lib/omg_status/alert/alarm.ex
- apps/omg_status/lib/omg_status/alert/alarm_handler.ex
- apps/omg_status/lib/status.ex
- apps/omg_watcher/lib/omg_watcher/api/account.ex
- apps/omg_watcher/lib/omg_watcher/monitor.ex
- apps/omg_watcher/lib/omg_watcher/supervisor.ex
- apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
- apps/omg_watcher/test/omg_watcher/integration/in_flight_exit_test.exs
- apps/omg_watcher/test/omg_watcher/integration/monitor_test.exs
- apps/omg_watcher_rpc/lib/web/controllers/account.ex
- apps/omg_watcher_rpc/lib/web/controllers/alarm.ex
- apps/omg_watcher_rpc/lib/web/controllers/status.ex
- apps/omg_watcher_rpc/lib/web/plugs/health.ex
- docker-compose.yml
-
- simplify the behavior of the Monitor to only restart the supervisor child proc if an alarm was raised and then cleared and that resulted in the supervisor exiting.
> refactor: move monitor one level up

- .circleci/config.yml
- apps/omg_child_chain_rpc/test/omg_child_chain_rpc/release_tasks/set_endpoint_test.exs
- apps/omg_watcher_rpc/test/omg_watcher_rpc/release_tasks/set_endpoint_test.exs
https://github.com/omisego/elixir-omg/issues/1025#issue-501398442
/
- Reset global app config after test
UNIT
> fix: flaky test that included a webserver 

- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_eth/lib/omg_eth/root_chain/submit_block.ex
> 1029 infura p3

- Makefile
- apps/omg_child_chain_rpc/priv/swagger/operator_api_specs.yaml
- apps/omg_watcher_rpc/priv/swagger/informational_api_specs.yaml
- apps/omg_watcher_rpc/priv/swagger/informational_api_specs/swagger.yaml
- apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml
swaps swagger-combine with swagger-cli
swaps swagger-combine with swagger-cli. I forgot to incl
- Regenerate api descriptions to avoid `refs`, because generators are not able to digest them
- Rename `Watcher's` to `Watchers` because generated code doesn't digest `'`
/
> Fix bundles

- docs-ui/index.html
- docs-ui/master/informational_api_specs.yaml
- docs-ui/master/operator_api_specs.yaml
- docs-ui/master/security_critical_api_specs.yaml
> fix: master specs and links

- docs-ui/index.html
> Gh pages update

- docker-compose-watcher.yml
this messed with my mind for a minute until i noticed the change. @achiurizo
> make postgres ports consistent among docker-compose files

- docs/standard_vs_in_flight_exits_interaction.md
Update the SE<>IFE document. Pretty much a re-write and then put a reference of old mechanism using `0.2` branch.
closes: #1108
> docs: update SE<>IFE interaction doc to new mechanism

- README.md
> fix: fixing links

- .circleci/ci_deploy.sh
Updates CircleCI configuration to point to a regional instead of zonal cluster
> fix: Update configuration to point to a regional cluster

- Makefile
- docker-compose-watcher.yml
Adds support fom Pre-Lumphini launch! 
- Stick to a image coming from the the sha we made the release from
- docs
tried it myself /
> feature: support pre-lumphini

- .circleci/config.yml
- README.md
- apps/omg_child_chain/lib/omg_child_chain/application.ex
- apps/omg_performance/test/fixtures.exs
- apps/omg_watcher/test/test_helper.exs
- apps/omg_watcher_info/lib/omg_watcher_info/application.ex
- docs/install.md
- mix.exs
Failing master nightly build
Adding ecto setup where needed and cleanup.
- OMG watcher breaches scope of testing and it needs ecto because of that
- Removed cookie setting
- Docs
/
> fix: ecto create

- .circleci/ci_deploy.sh
> Fix Watcher Info deployments

- .circleci/ci_deploy.sh
- .circleci/config.yml
- apps/omg_status/test/omg_status/release_tasks/set_tracer_test.exs
Increase the no-output timeout for barebuild integration tests
- fix buggy test
Nightly
> fix: nightly integration test needs more no output time

- snapshots.env
https://github.com/omisego/plasma-contracts/commit/73f526da384c4c2676ab509a4a891d42754aa722
> Update plasma contract sha to the latest

- apps/omg/lib/omg/output.ex
- apps/omg/lib/omg/utxo/position.ex
- apps/omg/test/support/conformance/property.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
- mix.lock
omisego/ex_plasma#21
This should fix the failing property tests
See omisego/ex_plasma#23, bumping to a commit having this fix
Also it requires some updates how `elixir-omg` calls into `ex_plasma`.
run property tests, see if CircleCI stops complaining about them failing
> fix: bump ex_plasma for the fix omisego/ex_plasma#21

- apps/omg_watcher/config/config.exs
Increases the block withholding threshold to 15 hours in the Watcher.
> feat: Increase block withholding threshold

- .circleci/config.yml
- Dockerfile.child_chain
- Dockerfile.watcher
- Dockerfile.watcher_info
- Makefile
- apps/omg_eth/test/support/dev_geth.ex
- bin/setup
- docker-compose.dev.yml
- docker-compose.yml
- docs/install.md
- snapshots.env
https://github.com/omisego/elixir-omg/issues/879
Bump images and unlock geth RPC.
Same tests should pass!
> bump geth 879 issue

- .circleci/config.yml
- Dockerfile.child_chain
- Dockerfile.watcher
- Dockerfile.watcher_info
- Makefile
- apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
- apps/omg_eth/test/fixtures.exs
- bin/setup
- docker-compose.dev.yml
- docker-compose.yml
- snapshots.env
Latest contracts, latest geth! Onwards and upwards!
> bump contracts and geth

- .circleci/config.yml
Publish docker images on version branches.
Need to merge this upstream into master.
> Publish docker image on version branches

- priv/perf/apps/load_test/lib/child_chain/utxos.ex
- priv/perf/apps/load_test/lib/service/faucet.ex
Add merge_utxos() functionality. Useful for utxo hygiene on the faucet
- Add LoadTest.ChildChain.Utxos.merge()
- Add LoadTest.Service.Faucet.merge_utxos()
> Add load test merge_utxos()

- apps/omg_child_chain/lib/omg_child_chain/datadog_event/contract_event_consumer.ex
- apps/omg_child_chain/lib/omg_child_chain/supervisor.ex
- apps/omg_watcher/lib/omg_watcher/datadog_event/contract_event_consumer.ex
- apps/omg_watcher/lib/omg_watcher/supervisor.ex
Fixes logging in contract event consumer
> fix: fix logging in contract event consumer

- apps/omg_watcher/lib/omg_watcher/event.ex
- apps/omg_watcher/lib/omg_watcher/exit_processor/exit_info.ex
- apps/omg_watcher/test/omg_watcher/exit_processor/persistence_test.exs
- apps/omg_watcher/test/support/exit_processor/test_helper.ex
Reverts omisego/elixir-omg#1479
> Revert "Add root chain transaction hash to InvalidExit and UnchallengedExit events"

- CHANGELOG.md
Update the changelog with changes from `v0.4.7-pre.0` to `v0.4.7-pre.1`
- Update `CHANGELOG.md` for v0.4.7-pre.1
N/A
> docs: changelog for v0.4.7 

- apps/omg_child_chain/lib/omg_child_chain/block_queue/measure.ex
Noticed we don't datadog balance!
Telemetry install handler
> install telemetry handler for authority balance

- docs-ui/1.0.0/info_api_specs.yaml
- docs-ui/1.0.0/operator_api_specs.yaml
- docs-ui/1.0.0/security_critical_api_specs.yaml
Deploy latest Swagger specs. Based on the specs found in [v1.0.0](https://github.com/omgnetwork/elixir-omg/tree/v1.0.0)
> docs: Swagger specs for v1.0.0

- .gitignore
- priv/cabbage/README.md
- priv/cabbage/apps/itest/test/itest/transactions_test.exs
Some minors fixes.
- better readme for cabbage test running
- update gitignore
- remove deplicated implementation on checking eth balance in transfer test
CI
> chore: minor fixes

- CHANGELOG.md
Change log doc for v1.0.2
` git log --format="%C(auto) %h %s" upstream/v1.0.1..upstream/boolafish/v1.0.2`
> docs: v1.0.2 change logs

- .gitmodules
the submodule should use the master branch
> fix integration tests

- .circleci/config.yml
- .gitmodules
:clipboard: 
Closes https://github.com/omgnetwork/elixir-omg/issues/1699
Associated: https://github.com/omgnetwork/specs/pull/5
Fix Tests on `master-v2` . Using submodules from branch [master-v2](https://github.com/omgnetwork/specs/tree/master-v2)
> Fix Failing tests on master-v2

- config/config.exs
> config filter sentry

- .circleci/config.yml
CI job on master was still using VERSION files
- remove the usage of VERSION file
tmp add CI step to try publish:
- watcher: https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/9222/workflows/a1d61f5d-cf44-4b80-909b-6c911ae79e1b/jobs/91569
- watcher-info: https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/9222/workflows/a1d61f5d-cf44-4b80-909b-6c911ae79e1b/jobs/91568
> fix: git tag

- .circleci/config.yml
> enable for master v2

- snapshot_reorg.env
> reorg snapshot

- .circleci/ci_publish.sh
- .circleci/config.yml
> enable master v2 branch

- .circleci/config.yml
> set cabbage env vars for reorg
